### ISSUE TITLE
walkthrough: Walkthrough charts fails to generate chart revisions

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1062]
### One-liner
When running walkthrough charts and trying to start chart revisions on live for the Global Carbon Budget (one that has close to 100 charts), I get an error.

### Environment

- `python -V`: 3.9.4
- Mac 11.6.4
- live

### Context & details
The issue happens on live grapher, but not on staging or local.

The log gets stuck at:
````
2023-05-03 09:26.49 [info     ] Creating VariablesUpdate object...
````

And the error I see on the browser is:
````
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pywebio/session/threadbased.py", line 86, in main_task
    target()
  File "/Users/prosado/Documents/owid/repos/etl/walkthrough/cli.py", line 61, in <lambda>
    lambda: phase_func(run_checks=run_checks, dummy_data=dummy_data),
  File "/Users/prosado/Documents/owid/repos/etl/walkthrough/charts.py", line 92, in app
    nav.run_app()
  File "/Users/prosado/Documents/owid/repos/etl/walkthrough/charts.py", line 397, in run_app
    self.final_steps()
  File "/Users/prosado/Documents/owid/repos/etl/walkthrough/charts.py", line 533, in final_steps
    charts = get_charts_to_update(self.variable_mapping)
  File "/Users/prosado/Documents/owid/repos/etl/etl/chart_revision/revision.py", line 29, in get_charts_to_update
    variables_update = VariablesUpdate(variable_mapping)
  File "/Users/prosado/Documents/owid/repos/etl/etl/chart_revision/variables.py", line 45, in __init__
    var_data = self._get_var_data_from_db()
  File "/Users/prosado/Documents/owid/repos/etl/etl/chart_revision/variables.py", line 89, in _get_var_data_from_db
    df = variable_data_df_from_s3(get_engine(), variable_ids=self.ids_all, workers=10)
  File "/Users/prosado/Documents/owid/repos/etl/backport/datasync/data_metadata.py", line 71, in variable_data_df_from_s3
    return add_entity_code_and_name(engine, df)
  File "/Users/prosado/Documents/owid/repos/etl/backport/datasync/data_metadata.py", line 89, in add_entity_code_and_name
    entities = pd.read_sql(q, engine, params={"entity_ids": df["entityId"].tolist()})
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/io/sql.py", line 590, in read_sql
    return pandas_sql.read_query(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "<string>", line 2, in execute
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 468, in warned
    return fn(*args, **kwargs)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3257, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: 
    SELECT
        id AS entityId,
        name AS entityName,
        code AS entityCode
    FROM entities
    WHERE id in %(entity_ids)s
    ]
[parameters: {'entity_ids': [273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, ... (22118018 characters truncated) ... 0, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80]}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
````

**Comment by Marigold** [comment]
Could you try changing [this line](https://github.com/owid/etl/blob/master/backport/datasync/data_metadata.py#L89) to 
```
entities = pd.read_sql(q, engine, params={"entity_ids": df["entityId"].unique().tolist()})
```
making it unique might work if we're lucky. If not I'll take a closer look at this and try to replicate it.

**Comment by pabloarosado** [comment]
Thanks a lot @Marigold, that fixed it. Although it's still quite slow, it takes a few minutes between selecting the datasets and submitting the chart revisions, so I suppose these queries will need to be optimised for big datasets.

**Comment by Marigold** [comment]
@pabloarosado if you feel like it would be useful to speed it up, just submit or reopen this issue and I'll look into it when I have some time.

**Comment by pabloarosado** [comment]
Thanks, I think we can live with the long wait (which will happen only for a few big datasets). Maybe we could simply signal in walkthrough charts that it may take some time to generate the revisions, otherwise it feels like nothing's happening.
