### ISSUE TITLE
walkthrough: error when executing `walkthrough charts` for the first time

### ISSUE THREAD

**Issue by paarriagadap** [owid/etl#1130]
### One-liner
When trying the new `walkthrough charts` tool in Streamlit for the first time, an error of execution appears

### Environment

- `python -V`: Python 3.11.1
- Operating system: macOS Ventura 13.3.1 (a)
- Working with local, staging or live: staging

### Context & details
The error only appeared the first time I executed it, before the error there was a message saying something like "loading x dataset" for 10+ seconds (I don't remember the exact name).

The error in the web browser:
```
🧑‍🍳 Chart revisions baker
OperationalError: (2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 0")
Traceback:
File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/Users/parriagadap/etl/walkthrough/charts_v2/__main__.py", line 100, in <module>
    DATASETS = get_datasets()
               ^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 194, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 223, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 248, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 302, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/walkthrough/charts_v2/__main__.py", line 30, in get_datasets
    datasets = get_all_datasets(archived=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/etl/db.py", line 156, in get_all_datasets
    db_conn = get_connection()
              ^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/etl/db.py", line 22, in get_connection
    return MySQLdb.connect(
           ^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
```

In the terminal:
```
(etl-py3.11) parriagadap@Pablos-MacBook-Pro etl % walkthrough charts
Walkthrough has been opened at http://localhost:8082/

      👋 Welcome to Streamlit!

      If you’d like to receive helpful onboarding emails, news, offers, promotions,
      and the occasional swag, please enter your email address below. Otherwise,
      leave this field blank.

      Email:  

  You can find our privacy policy at https://streamlit.io/privacy-policy

  Summary:
  - This open source library collects usage statistics.
  - We cannot see and do not store information contained inside Streamlit apps,
    such as text, charts, images, etc.
  - Telemetry data is stored in servers in the United States.
  - If you'd like to opt out, add the following to ~/.streamlit/config.toml,
    creating that file if necessary:

    [browser]
    gatherUsageStats = false


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8082
  Network URL: http://192.168.1.127:8082

2023-05-19 09:46:02.360 Uncaught app exception
Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 87, in get
    entry_bytes = self._read_from_mem_cache(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 137, in _read_from_mem_cache
    raise CacheStorageKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 588, in read_result
    pickled_entry = self.storage.get(key)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 89, in get
    entry_bytes = self._persist_storage.get(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/local_disk_cache_storage.py", line 155, in get
    raise CacheStorageKeyNotFoundError(
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Local disk cache storage is disabled (persist=None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 245, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 590, in read_result
    raise CacheKeyNotFoundError(str(e)) from e
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError: Local disk cache storage is disabled (persist=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 87, in get
    entry_bytes = self._read_from_mem_cache(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 137, in _read_from_mem_cache
    raise CacheStorageKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 588, in read_result
    pickled_entry = self.storage.get(key)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 89, in get
    entry_bytes = self._persist_storage.get(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/storage/local_disk_cache_storage.py", line 155, in get
    raise CacheStorageKeyNotFoundError(
streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Local disk cache storage is disabled (persist=None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 293, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 590, in read_result
    raise CacheKeyNotFoundError(str(e)) from e
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError: Local disk cache storage is disabled (persist=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/parriagadap/etl/walkthrough/charts_v2/__main__.py", line 100, in <module>
    DATASETS = get_datasets()
               ^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 194, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 223, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 248, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 302, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/walkthrough/charts_v2/__main__.py", line 30, in get_datasets
    datasets = get_all_datasets(archived=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/db.py", line 156, in get_all_datasets
    db_conn = get_connection()
              ^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/db.py", line 22, in get_connection
    return MySQLdb.connect(
           ^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 0")
```

**Comment by lucasrodes** [comment]
The error seems to come from the connection to the database. The easiest solution is just to refresh the app.

I improved the error message in https://github.com/owid/etl/pull/1135.
