### ISSUE TITLE
Grapher step is not working when country and year are in index

### ISSUE THREAD

**Issue by paarriagadap** [owid/etl#1156]
[Published on Slack](https://owid.slack.com/archives/C46U9LXRR/p1685025735350539)

Grapher step is failing when I try to run a dataset on the ETL. It is because the step tries to find `year` and it's on the index.

I commonly add this command before saving into a Garden dataset: 
`df = df.set_index(["country", "year"], verify_integrity=True).sort_index()`

Which never generated any problem. Now I get this:

```
(etl-py3.11) parriagadap@Pablos-MacBook-Pro etl % etl ethnic
Detecting which steps need rebuilding...
OK (2s)                                                               
Running 1 steps:
1. data://grapher/eth/2023-03-15/ethnic_power_relations...
2023-05-25 15:36:40,052 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'year'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/run_python_step.py", line 34, in main
    _import_and_run(path, dest_dir)
  File "/Users/parriagadap/etl/etl/run_python_step.py", line 52, in _import_and_run
    module.run(dest_dir)
  File "/Users/parriagadap/etl/etl/steps/data/grapher/eth/2023-03-15/ethnic_power_relations.py", line 34, in run
    grapher_checks(ds_garden)
  File "/Users/parriagadap/etl/etl/helpers.py", line 73, in grapher_checks
    assert tab["year"].dtype in gh.INT_TYPES, f"year must be of an integer type but was: {tab['country'].dtype}"
           ~~~^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'year'

COMMAND: poetry run run_python_step data://grapher/eth/2023-03-15/ethnic_power_relations /Users/parriagadap/etl/data/grapher/eth/2023-03-15/ethnic_power_relations
```

As I needed to push to Grapher, I preferred to comment the set_index code, as in https://github.com/owid/etl/pull/1154 and https://github.com/owid/etl/pull/1155

**Comment by Marigold** [comment]
Fixed on master and uncommented those `...reset_index()` methods in lgbti and ethnic. Thanks for reporting @paarriagadap !
