### ISSUE TITLE
Deploy failure: variable must be named to have metadata

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#1280]
Investigating a current deploy failure. Looks like a problem with the Table class in an edge case.

```
1. grapher://grapher/artificial_intelligence/2023-06-14/ai_adoption...
  | 2023-06-28 09:18:32 [info     ] upsert_dataset.verify_namespace namespace=artificial_intelligence
  | 2023-06-28 09:18:32 [info     ] upsert_dataset.upsert_dataset.start short_name=ai_adoption
  | 2023-06-28 09:18:32 [info     ] upsert_dataset.upsert_dataset.end id=6084 short_name=ai_adoption
  | 2023-06-28 09:18:33 [info     ] Creating entities in DB        countries={'All Geographies'}
  | Traceback (most recent call last):
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1105, in __setitem__
  | self._set_with_engine(key, value)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1175, in _set_with_engine
  | loc = self.index.get_loc(key)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 394, in get_loc
  | self._check_indexing_error(key)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5968, in _check_indexing_error
  | raise InvalidIndexError(key)
  | pandas.errors.InvalidIndexError: 0      True
  | 1     False
  | 2     False
  | 3     False
  | 4     False
  | 5     False
  | 6      True
  | 7     False
  | 8     False
  | 9     False
  | 10    False
  | 11    False
  | Name: country, dtype: bool
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/home/owid/etl/.venv/bin/etl", line 6, in <module>
  | sys.exit(main_cli())
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
  | return self.main(*args, **kwargs)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
  | rv = self.invoke(ctx)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
  | return __callback(*args, **kwargs)
  | File "/home/owid/etl/etl/command.py", line 119, in main_cli
  | main(**kwargs)  # type: ignore
  | File "/home/owid/etl/etl/command.py", line 147, in main
  | run_dag(
  | File "/home/owid/etl/etl/command.py", line 245, in run_dag
  | time_taken = timed_run(lambda: step.run())
  | File "/home/owid/etl/etl/command.py", line 252, in timed_run
  | f()
  | File "/home/owid/etl/etl/command.py", line 245, in <lambda>
  | time_taken = timed_run(lambda: step.run())
  | File "/home/owid/etl/etl/steps/__init__.py", line 683, in run
  | table = gh._adapt_table_for_grapher(table)
  | File "/home/owid/etl/etl/grapher_helpers.py", line 414, in _adapt_table_for_grapher
  | table["entity_id"] = country_to_entity_id(table[country_col], create_entities=True)
  | File "/home/owid/etl/etl/grapher_helpers.py", line 254, in country_to_entity_id
  | entity_id[ix] = country[ix].map(_get_and_create_entities_in_db(set(country[ix]))).astype(float)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1162, in __setitem__
  | self._where(~key, value, inplace=True)
  | File "/home/owid/etl/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 9645, in _where
  | cond = cond.fillna(fill_value)
  | File "/home/owid/etl/lib/catalog/owid/catalog/variables.py", line 220, in fillna
  | variable._fields[variable_name] = combine_variables_metadata(
  | File "/home/owid/etl/lib/catalog/owid/catalog/variables.py", line 557, in combine_variables_metadata
  | variables_only = [variable for variable in variables if hasattr(variable, "metadata")]
  | File "/home/owid/etl/lib/catalog/owid/catalog/variables.py", line 557, in <listcomp>
  | variables_only = [variable for variable in variables if hasattr(variable, "metadata")]
  | File "/home/owid/etl/lib/catalog/owid/catalog/variables.py", line 122, in metadata
  | vm = self._fields[self.checked_name]
  | File "/home/owid/etl/lib/catalog/owid/catalog/variables.py", line 102, in checked_name
  | raise ValueError("variable must be named to have metadata")
  | ValueError: variable must be named to have metadata
```

**Comment by larsyencken** [comment]
The error occurs when in `country_to_entity_id()` when you need to create an entity in the DB...

**Comment by larsyencken** [comment]
The failure can be isolated to something like this statement:

`catalog.Variable([1, 2, None]).fillna(0)`
