### ISSUE TITLE
Build failure: grapher://grapher/covid/latest/vaccinations

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#1401]
Prod build is currently failing due to the grapher step for covid vaccination data:

```
3. grapher://grapher/covid/latest/vaccinations...
2023-08-01 08:03:46 [info     ] upsert_dataset.verify_namespace namespace=covid
2023-08-01 08:03:46 [info     ] upsert_dataset.upsert_dataset.start short_name=vaccinations
2023-08-01 08:03:46 [info     ] upsert_dataset.upsert_dataset.end id=6153 short_name=vaccinations
2023-08-01 08:03:51 [info     ] upsert_table.upserted_variable id=738597 size=46617 title=total_boosters
2023-08-01 08:03:51 [info     ] upsert_table.upserted_variable id=738594 size=78231 title=total_vaccinations
2023-08-01 08:03:52 [info     ] upsert_table.upserted_variable id=738596 size=71495 title=people_fully_vaccinated
2023-08-01 08:03:52 [info     ] upsert_table.upserted_variable id=738595 size=74956 title=people_vaccinated
2023-08-01 08:03:53 [info     ] upsert_table.upserted_variable id=738598 size=64577 title=new_vaccinations
2023-08-01 08:03:53 [info     ] upsert_table.upserted_variable id=738601 size=78231 title=total_vaccinations_per_hundred
2023-08-01 08:03:53 [info     ] upsert_table.upserted_variable id=738599 size=175829 title=new_vaccinations_smoothed
2023-08-01 08:03:53 [info     ] upsert_table.upserted_variable id=738602 size=74956 title=people_vaccinated_per_hundred
2023-08-01 08:03:54 [info     ] upsert_table.upserted_variable id=738600 size=175657 title=new_people_vaccinated_smoothed
2023-08-01 08:03:54 [info     ] upsert_table.upserted_variable id=738603 size=71495 title=people_fully_vaccinated_per_hundred
2023-08-01 08:03:54 [info     ] upsert_table.upserted_variable id=738604 size=46617 title=total_boosters_per_hundred
Traceback (most recent call last):
  File "/home/owid/etl/.venv/bin/etl", line 6, in <module>
    sys.exit(main_cli())
  File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/owid/etl/etl/command.py", line 129, in main_cli
    main(**kwargs)  # type: ignore
  File "/home/owid/etl/etl/command.py", line 158, in main
    run_dag(
  File "/home/owid/etl/etl/command.py", line 260, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/home/owid/etl/etl/command.py", line 296, in timed_run
    f()
  File "/home/owid/etl/etl/command.py", line 260, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/home/owid/etl/etl/steps/__init__.py", line 742, in run
    variable_upsert_results = [future.result() for future in concurrent.futures.as_completed(futures)]
  File "/home/owid/etl/etl/steps/__init__.py", line 742, in <listcomp>
    variable_upsert_results = [future.result() for future in concurrent.futures.as_completed(futures)]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/owid/etl/etl/steps/__init__.py", line 731, in <lambda>
    upsert = lambda t: gi.upsert_table(  # noqa: E731
  File "/home/owid/etl/etl/grapher_import.py", line 226, in upsert_table
    variable = gm.Variable.from_variable_metadata(
  File "/home/owid/etl/etl/grapher_model.py", line 847, in from_variable_metadata
    assert metadata.display
AssertionError
2023-08-01 08:03:54 [info     ] upsert_table.upserted_variable id=738607 size=931 title=share_of_boosters
2023-08-01 08:03:55 [info     ] upsert_table.upserted_variable id=738605 size=175829 title=new_vaccinations_smoothed_per_million
2023-08-01 08:03:55 [info     ] upsert_table.upserted_variable id=738608 size=74956 title=people_unvaccinated
🚨 Error: The command exited with status 1
```

**Comment by larsyencken** [comment]
Taking a look since Mojmir's away
