### ISSUE TITLE
Build failure: data://garden/ihme_gbd/2023-06-14/prevalence_dalys_world

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#1402]
I get this error trying to rebuild this step with `--force`:

```
7. data://garden/ihme_gbd/2023-06-14/prevalence_dalys_world...
2023-08-01 10:13:46 [info     ] prevalence_dalys_world: start
2023-08-01 10:13:46 [info     ] prevalence_dalys_world: build tables
2023-08-01 10:13:46,541 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 34, in main
    _import_and_run(path, dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 52, in _import_and_run
    module.run(dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/ihme_gbd/2023-06-14/prevalence_dalys_world.py", line 31, in run
    tb_dalys = make_table_dalys(ds_dalys)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/ihme_gbd/2023-06-14/prevalence_dalys_world.py", line 62, in make_table_dalys
    tb_cause = ds[cause].reset_index()
               ~~^^^^^^^
  File "/Users/lars/Documents/owid/etl/lib/catalog/owid/catalog/datasets.py", line 156, in __getitem__
    raise KeyError(f"Table `{name}` not found, available tables: {', '.join(self.table_names)}")
KeyError: 'Table `anxiety_disorders__both_sexes__age_standardized` not found, available tables: ...
```

**Comment by spoonerf** [comment]
Should be fixed with #1399

**Comment by larsyencken** [comment]
Ah, nice! Yes, please do 🙂

**Comment by spoonerf** [comment]
Looks like it's working now, so I'll close this.
