### ISSUE TITLE
Running a snapshot step fails when passing an origin where date_published is a year

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1473]
Running a snapshot step fails when passing an origin where date_published is a year.

When running `python snapshots/animal_welfare/2023-08-14/number_of_farmed_fishes.py` I get the error:
```
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/snapshots/animal_welfare/2023-08-14/number_of_farmed_fishes.py", line 32, in <module>
    main()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/snapshots/animal_welfare/2023-08-14/number_of_farmed_fishes.py", line 22, in main
    snap = Snapshot(f"animal_welfare/{SNAPSHOT_VERSION}/number_of_farmed_fishes.xlsx")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/etl/snapshot.py", line 63, in __init__
    self.metadata = SnapshotMeta.load_from_yaml(self.metadata_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/etl/snapshot.py", line 210, in load_from_yaml
    meta["origin"] = Origin.from_dict(meta["origin"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/dataclasses_json/core.py", line 208, in _decode_dataclass
    return cls(**init_kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in __init__
  File "/Users/prosado/Documents/owid/repos/etl/lib/catalog/owid/catalog/meta.py", line 148, in __post_init__
    if self.date_published != "latest" and not is_year_or_date(self.date_published):
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/lib/catalog/owid/catalog/meta.py", line 503, in is_year_or_date
    if re.match(date_pattern, s) or re.match(year_pattern, s):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'
```

**Comment by Marigold** [comment]
Fixed by this https://github.com/owid/etl/commit/b34863f2a7dd2119974c1cc2c858b6e0b9f82c2c.
