### ISSUE TITLE
docs: Running `mkdocs serve` fails because of `api/python.ipynb`

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1580]
### One-liner
Running `mkdocs serve` fails with an error. The error disappears when removing the file `api/python.ipynb`.

### Context & details
Full log when running `mkdocs serve`:
```
INFO    -  DeprecationWarning: Jupyter is migrating its paths to use standard
           platformdirs
           given by the platformdirs library.  To remove this warning and
           see the appropriate new directories, set the environment variable
           `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
           The use of platformdirs will be the default in `jupyter_core` v6
             File
           "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py",
           line 89, in deprecation
               warnings.warn(message, DeprecationWarning, stacklevel=stacklevel
           + 1)
             File
           "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/jupyter_client/connect.py",
           line 20, in
               from jupyter_core.paths import jupyter_data_dir,
           jupyter_runtime_dir, secure_write
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included
           in the "nav" configuration:
             - old-readme.md
             - architecture/design/index.md
             - architecture/workflow/publish.md
             - architecture/workflow/other-steps/index.md
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'api/', it
           was left as is. Did you mean 'api/index.md'?
WARNING -  Doc file 'old-readme.md' contains a relative link
           'docs/future-architecture.png', but the target is not found among
           documentation files.
INFO    -  Converting notebook (execute=False):
           /Users/prosado/Documents/owid/repos/etl/docs/api/python.ipynb
INFO    -  DeprecationWarning: defusedxml.cElementTree is deprecated, import
           from defusedxml.ElementTree instead.
             File
           "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs_jupyter/convert.py",
           line 16, in add_anchor_lower_id
               from defusedxml import cElementTree as ElementTree
             File
           "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/defusedxml/cElementTree.py",
           line 38, in <module>
               warnings.warn(
ERROR   -  Error reading page 'api/python.ipynb': No module named
           'jupyter_contrib_nbextensions'
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs_jupyter/plugin.py", line 110, in new_render
    toc, title = get_nb_toc(page.file.abs_src_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs_jupyter/plugin.py", line 147, in get_nb_toc
    body = convert.nb2md(fpath)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs_jupyter/nbconvert2.py", line 144, in nb2md
    exporter = MarkdownExporter(
               ^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 353, in __init__
    super().__init__(config=config, **kw)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 117, in __init__
    self._init_preprocessors()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 519, in _init_preprocessors
    super()._init_preprocessors()
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 278, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 238, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
```

After that, I did `poetry add jupyter_contrib_nbextensions` and tried again `mkdocs serve`, and now I get a different error. Full log:
```
INFO    -  DeprecationWarning: Jupyter is migrating its paths to use standard
           platformdirs
           given by the platformdirs library.  To remove this warning and
           see the appropriate new directories, set the environment variable
           `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
           The use of platformdirs will be the default in `jupyter_core` v6
             File
           "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py",
           line 89, in deprecation
               warnings.warn(message, DeprecationWarning, stacklevel=stacklevel
           + 1)
             File
           "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/jupyter_client/connect.py",
           line 20, in
               from jupyter_core.paths import jupyter_data_dir,
           jupyter_runtime_dir, secure_write
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 59, in serve
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 47, in get_config
    config = load_config(
             ^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/config/base.py", line 378, in load_config
    errors, warnings = cfg.validate()
                       ^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/config/base.py", line 230, in validate
    run_failed, run_warnings = self._validate()
                               ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/config/config_options.py", line 182, in validate
    return self.run_validation(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/config/config_options.py", line 1064, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/config/config_options.py", line 1100, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs/config/config_options.py", line 1118, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs_jupyter/plugin.py", line 12, in <module>
    from . import convert
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs_jupyter/convert.py", line 51, in <module>
    from .nbconvert2 import *
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/mkdocs_jupyter/nbconvert2.py", line 20, in <module>
    from nbconvert.nbconvertapp import NbConvertApp
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 194, in <module>
    class NbConvertApp(JupyterApp):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 287, in NbConvertApp
    formats=get_export_names()
            ^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/exporters/base.py", line 149, in get_export_names
    e = get_exporter(exporter_name)(config=config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/nbconvert/exporters/base.py", line 100, in get_exporter
    exporter = entrypoints.get_single("nbconvert.exporters", name).load()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/entrypoints.py", line 79, in load
    mod = import_module(self.module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/jupyter_contrib_nbextensions/__init__.py", line 5, in <module>
    import jupyter_nbextensions_configurator
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/jupyter_nbextensions_configurator/__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'
```

The workaround is to delete the file `docs/api/python.ipynb`.

**Comment by pabloarosado** [comment]
May be fixed after updating jupyter dependencies.

**Comment by Marigold** [comment]
I've tried many combinations of dependencies to make this work, but I couldn't get past `ModuleNotFoundError: No module named 'notebook.base'`. It looks like we'd have to downgrade to [notebook 6](https://stackoverflow.com/questions/76893872/modulenotfounderror-no-module-named-notebook-base-when-installing-nbextension). The only solution was removing jupytext. This should be [fixed by this PR](https://github.com/owid/etl/pull/1618).
