### ISSUE TITLE
grapher: Object of type uint64 is not JSON serializable

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1687]
I am getting a `(builtins.TypeError) Object of type uint64 is not JSON serializable` error when running the grapher step from ETL into my staging server.

I am working on branch `data/hmd-derived-survivor-ages`, and running 

```
~ ENV=.env.lucas etl survivor_percentiles --grapher
```

I thought there could be something wrong with the metadata yaml file, but it looks just fine.

Full error message: 

```
~ ENV=.env.lucas etl survivor_percentiles --grapher
--- Detecting which steps need rebuilding...
OK (1.4s)
--- Running 1 steps:
--- 1. grapher://grapher/demography/2023-09-27/survivor_percentiles...
2023-09-28 16:29:16 [info     ] upsert_dataset.verify_namespace namespace=demography
2023-09-28 16:29:17 [info     ] upsert_dataset.upsert_dataset.start short_name=survivor_percentiles
2023-09-28 16:29:17 [info     ] upsert_dataset.upsert_dataset.end id=6210 short_name=survivor_percentiles
2023-09-28 16:29:23,284 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 2669, in process
    serialized = json_serializer(value)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type uint64 is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/bin/etl", line 6, in <module>
    sys.exit(main_cli())
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lucas/repos/etl/etl/command.py", line 150, in main_cli
    main(**kwargs)  # type: ignore
  File "/home/lucas/repos/etl/etl/command.py", line 179, in main
    run_dag(
  File "/home/lucas/repos/etl/etl/command.py", line 286, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/command.py", line 322, in timed_run
    f()
  File "/home/lucas/repos/etl/etl/command.py", line 286, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 788, in run
    variable_upsert_results = [future.result() for future in concurrent.futures.as_completed(futures)]
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 788, in <listcomp>
    variable_upsert_results = [future.result() for future in concurrent.futures.as_completed(futures)]
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 777, in <lambda>
    upsert = lambda t: gi.upsert_table(  # noqa: E731
  File "/home/lucas/repos/etl/etl/grapher_import.py", line 266, in upsert_table
    ).upsert(session)
  File "/home/lucas/repos/etl/etl/grapher_model.py", line 991, in upsert
    return session.exec(q).one()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 60, in exec
    results = super().execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1665, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2264, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2253, in _autoflush
    self.flush()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1816, in _execute_context
    self._handle_dbapi_exception(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 2669, in process
    serialized = json_serializer(value)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
sqlalchemy.exc.StatementError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(builtins.TypeError) Object of type uint64 is not JSON serializable
[SQL: INSERT INTO variables (`datasetId`, name, `shortName`, description, unit, `createdAt`, `updatedAt`, coverage, timespan, `sourceId`, display, `columnOrder`, code, `shortUnit`, `originalMetadata`, `grapherConfigAdmin`, `grapherConfigETL`, `catalogPath`, dimensions, `schemaVersion`, `processingLog`, `titlePublic`, `titleVariant`, `attributionShort`, attribution, `descriptionShort`, `descriptionFromProducer`, `descriptionKey`, `descriptionProcessing`, licenses, license, `processingLevel`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: [{'timespan': '1835-2022', 'updatedAt': datetime.datetime(2023, 9, 28, 14, 29, 18, 438338), 'display': {'unit': 'years'}, 'dimensions': {'originalShor ... (931 characters truncated) ... ionFromProducer': None, 'grapherConfigETL': None, 'attributionShort': None, 'licenses': None, 'description': None, 'sourceId': None, 'license': None}]]
```

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/etl/commit/9195bbe496f6fdb89da1457f69818fdbc72dbee7. `dimensions` field contained numpy types that can't be inserted into MySQL.
