### ISSUE TITLE
groupby with observed is False fails instead of raising a warning

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1726]
When trying to execute `garden/eia/2023-07-10/energy_consumption` I get the following error:

```
--- 1. data://garden/eia/2023-07-10/energy_consumption...
2023-10-04 13:30:39,498 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/etl/run_python_step.py", line 34, in main
    _import_and_run(path, dest_dir)
  File "/Users/prosado/Documents/owid/repos/etl/etl/run_python_step.py", line 52, in _import_and_run
    module.run(dest_dir)
  File "/Users/prosado/Documents/owid/repos/etl/etl/steps/data/garden/eia/2023-07-10/energy_consumption.py", line 445, in run
    tb = add_region_aggregates(
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/etl/steps/data/garden/eia/2023-07-10/energy_consumption.py", line 390, in add_region_aggregates
    data_for_region = geo.add_region_aggregates(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/etl/data_helpers/geo.py", line 327, in add_region_aggregates
    df_added = groupby_agg(
               ^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/lib/datautils/owid/datautils/dataframes.py", line 339, in groupby_agg
    num_nans_detected = count_missing_in_groups(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/lib/datautils/owid/datautils/dataframes.py", line 367, in count_missing_in_groups
    df[nan_columns]
  File "/Users/prosado/Documents/owid/repos/etl/lib/catalog/owid/catalog/tables.py", line 920, in groupby
    by_type = self[by].dtype if by in self.columns.tolist() else self.index.dtype[by]  # type: ignore
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Variable is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

```

@Marigold I think there are two issues here. One is that, even if `observed=True`, the warning is raised (I'll quickly fix this now). That fixes it for this step, but I think that the way we check for the type of the columns has a bug. If you impose `observed=False` (in `datautils.dataframes.groupby_agg`), you get the same error again. If this becomes too problematic, as you suggested, we can just always impose `observed=True` instead of raising a warning.

**Comment by Marigold** [comment]
@pabloarosado it works now with your fix. Can we close it?

**Comment by pabloarosado** [comment]
I think in some (probably unusual) circumstances, the way we check if there are categorical variables doesn't work. To replicate this, edit the `datautils.dataframes` module and, inside the function `groupby_agg` set
```
    groupby_kwargs = {
        "dropna": False,
        "observed": False,
    }
```
Then, when you run `garden/eia/2023-07-10/energy_consumption`, you'll get the error `TypeError: unhashable type: 'Variable'`. It's probably a silly thing, but I haven't looked into it in detail.

**Comment by Marigold** [comment]
Oh right, I saw the same error, but then couldn't find it. It's using actual series instead of name of the column 🤷 Anyway, I pushed a fix that should deal with it and also other weird groupby types like `pd.Grouper`.
