### ISSUE TITLE
`owid-catalog` can't read a table outside of ETL

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1789]
When reading a table within ETL using `owid-catalog` there are no problems. But when trying to read a table from an external repos (like `co2-data`), `owid-catalog` fails.

To replicate, create a brand new virtual environment, install the latest `owid-catalog`, and in a python console, run:
```
from owid import catalog
catalog.find("global_carbon_budget").sort_values("version", ascending=False).iloc[0].load()
```
The `load` is what causes the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/owid/catalog/catalogs.py", line 363, in load
    return Table.read(uri)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/owid/catalog/tables.py", line 169, in read
    table = cls.read_feather(path)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/owid/catalog/tables.py", line 352, in read_feather
    cls._add_metadata(df, path)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/owid/catalog/tables.py", line 331, in _add_metadata
    df._set_fields_from_dict(fields)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/owid/catalog/tables.py", line 377, in _set_fields_from_dict
    self._fields = defaultdict(VariableMeta, {k: VariableMeta.from_dict(v) for k, v in fields.items()})
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/owid/catalog/tables.py", line 377, in <dictcomp>
    self._fields = defaultdict(VariableMeta, {k: VariableMeta.from_dict(v) for k, v in fields.items()})
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 219, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 290, in _decode_generic
    xs = _decode_items(_get_type_arg_param(type_, 0), value, infer_missing)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 378, in _decode_items
    return list(_decode_item(type_args, x) for x in xs)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 378, in <genexpr>
    return list(_decode_item(type_args, x) for x in xs)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 371, in _decode_item
    return _decode_dataclass(type_arg, x, infer_missing)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 219, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 312, in _decode_generic
    res = _support_extended_types(type_arg, value)
  File "/Users/prosado/Documents/owid/repos/tmp/venv/lib/python3.9/site-packages/dataclasses_json/core.py", line 249, in _support_extended_types
    if isinstance(field_value, field_type)
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by Marigold** [comment]
I can't replicate it with a fresh new virtualenv and python 3.10. What's your python version and `dataclass-json` version (get it with `pip freeze | grep dataclass`)?

**Comment by pabloarosado** [comment]
In the co2-data repos I'm using Python 3.9.4 (which should in theory be supported by `owid-catalog`), and `dataclasses-json==0.6.1`.
