### ISSUE TITLE
bug: MySQLdb.IntegrityError

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1829]
When running `ENV=.env.lucas etl life_expectancy --grapher`, I get the following error (after all the upsert_table.uploaded_to_s3 steps):

```
2023-10-20 10:09:11 [error    ] Error encountered during import: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`owid`.`tags_variables_topic_tags`, CONSTRAINT `tags_variables_topic_tags_ibfk_2` FOREIGN KEY (`variableId`) REFERENCES `variables` (`id`))')
2023-10-20 10:09:11 [error    ] Rolling back changes...
Traceback (most recent call last):
  File "/home/lucas/repos/etl/etl/db.py", line 49, in open_db
    yield DBUtils(cursor)
  File "/home/lucas/repos/etl/etl/grapher_import.py", line 405, in cleanup_ghost_variables
    db.cursor.execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`owid`.`tags_variables_topic_tags`, CONSTRAINT `tags_variables_topic_tags_ibfk_2` FOREIGN KEY (`variableId`) REFERENCES `variables` (`id`))')
2023-10-20 10:09:11,428 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/bin/etl", line 6, in <module>
    sys.exit(main_cli())
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lucas/repos/etl/etl/command.py", line 150, in main_cli
    main(**kwargs)  # type: ignore
  File "/home/lucas/repos/etl/etl/command.py", line 179, in main
    run_dag(
  File "/home/lucas/repos/etl/etl/command.py", line 286, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/command.py", line 322, in timed_run
    f()
  File "/home/lucas/repos/etl/etl/command.py", line 286, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 806, in run
    self._cleanup_ghost_resources(dataset_upsert_results, variable_upsert_results)
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 833, in _cleanup_ghost_resources
    gi.cleanup_ghost_variables(
  File "/home/lucas/repos/etl/etl/grapher_import.py", line 405, in cleanup_ghost_variables
    db.cursor.execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`owid`.`tags_variables_topic_tags`, CONSTRAINT `tags_variables_topic_tags_ibfk_2` FOREIGN KEY (`variableId`) REFERENCES `variables` (`id`))')
```

**Comment by lucasrodes** [comment]
@Marigold 
I think I can recreate it.

In branch `enhance/le-metadata-3`, it fails if I run

```
ENV=.env.lucas etl life_expectancy --grapher
```

However, if I comment the following lines it does work.

https://github.com/owid/etl/blob/9471bdc5fb252a449bb8d38d19e305ac61c4f7f4/etl/steps/data/garden/demography/2023-10-09/life_expectancy.py#L95-L99

^In these lines I basically filter a dimension (`age in [10, 25, 45]`)

**Comment by Marigold** [comment]
I can't replicate it. Leaving this issue open until we either run into it again or owidbot closes it.
