### ISSUE TITLE
NameError: name '_mysql' is not defined error when running ETL steps

### ISSUE THREAD

**Issue by paarriagadap** [owid/etl#1888]
After following the [ETL settings guide here](https://docs.owid.io/projects/etl/getting-started/working-environment/) in 1 November 2023, I found a problem called 
```
NameError: name '_mysql' is not defined
```
when running any step.

The full error is shown below:
```
(etl-py3.11) parriagadap@Pablos-MacBook-Pro etl % etl un_members
2023-11-01 12:18:24,056 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/mysql-client/lib/libmysqlclient.21.dylib
  Referenced from: <48CF6E60-E933-3F36-837A-F553E05F15B2> /Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-darwin.so
  Reason: tried: '/opt/homebrew/opt/mysql-client/lib/libmysqlclient.21.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/mysql-client/lib/libmysqlclient.21.dylib' (no such file), '/opt/homebrew/opt/mysql-client/lib/libmysqlclient.21.dylib' (no such file), '/usr/local/lib/libmysqlclient.21.dylib' (no such file), '/usr/lib/libmysqlclient.21.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/mysql-client/8.1.0/lib/libmysqlclient.21.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/mysql-client/8.1.0/lib/libmysqlclient.21.dylib' (no such file), '/opt/homebrew/Cellar/mysql-client/8.1.0/lib/libmysqlclient.21.dylib' (no such file), '/usr/local/lib/libmysqlclient.21.dylib' (no such file), '/usr/lib/libmysqlclient.21.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/bin/etl", line 3, in <module>
    from etl.command import main_cli
  File "/Users/parriagadap/etl/etl/command.py", line 21, in <module>
    from etl.steps import (
  File "/Users/parriagadap/etl/etl/steps/__init__.py", line 32, in <module>
    from etl import grapher_helpers as gh
  File "/Users/parriagadap/etl/etl/grapher_helpers.py", line 16, in <module>
    from etl.db import get_connection, get_engine
  File "/Users/parriagadap/etl/etl/db.py", line 8, in <module>
    import MySQLdb
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
                  ^^^^^^
NameError: name '_mysql' is not defined
```

**Comment by paarriagadap** [comment]
**Solved:**

@Marigold, modifying a solution by @ikesau, found a fix by copying a mysql-client file to the version the error is asking for:

```
cp /opt/homebrew/opt/mysql-client/lib/libmysqlclient.22.dylib /opt/homebrew/opt/mysql-client/lib/libmysqlclient.21.dylib
```
