### ISSUE TITLE
:bug: Failing garden step for tuberculosis data

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2073]
```
--- Detecting which steps need rebuilding...
OK (13.3s)
--- Running 6 steps:
--- 1. data://garden/tuberculosis/2023-11-27/outcomes_disagg...
2023-12-13 01:28:59,598 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 34, in main
    _import_and_run(path, dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 54, in _import_and_run
    module.run(dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/tuberculosis/2023-11-27/outcomes_disagg.py", line 48, in run
    tb = add_region_sum_aggregates(tb, ds_regions, ds_income_groups)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/tuberculosis/2023-11-27/outcomes_disagg.py", line 107, in add_region_sum_aggregates
    gr_reg = geo.add_region_aggregates(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/data_helpers/geo.py", line 399, in add_region_aggregates
    if mask_countries_present.any():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 11614, in any
    return NDFrame.any(self, axis, bool_only, skipna, level, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 11174, in any
    return self._logical_func(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 11157, in _logical_func
    return self._reduce(
           ^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 4797, in _reduce
    return delegate._reduce(name, skipna=skipna, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/arrays/base.py", line 1435, in _reduce
    raise TypeError(
TypeError: 'Categorical' with dtype category does not support reduction 'any'

COMMAND: poetry run run_python_step data://garden/tuberculosis/2023-11-27/outcomes_disagg /Users/lars/Documents/owid/etl/data/garden/tuberculosis/2023-11-27/outcomes_disagg
```

**Comment by pabloarosado** [comment]
Bloody pandas categorical dtype... https://github.com/owid/etl/pull/2075 should fix it.

**Comment by larsyencken** [comment]
Thank you Pablo! 🙏
