### ISSUE TITLE
HMD STMF stopped publishing excess mortality data for most countries

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2149]
ETL hit this [assertion error](https://app.bugsnag.com/our-world-in-data/etl/errors/659239c6da461700083319c7?event_id=659239c600cf50c2e52b0000&i=sk&m=nw)
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "click/core.py", line 1157, in __call__
          return self.main(*args, **kwargs)
  File "click/core.py", line 1078, in main
                      rv = self.invoke(ctx)
  File "click/core.py", line 1434, in invoke
              return ctx.invoke(self.callback, **ctx.params)
  File "click/core.py", line 783, in invoke
                  return __callback(*args, **kwargs)
  File "etl/run_python_step.py", line 34, in main
          _import_and_run(path, dest_dir)
  File "etl/run_python_step.py", line 54, in _import_and_run
      module.run(dest_dir)
  File "etl/steps/data/garden/excess_mortality/latest/hmd_stmf.py", line 47, in run
      df = process(df)
  File "etl/steps/data/garden/excess_mortality/latest/hmd_stmf.py", line 87, in process
      df = add_uk(df)
  File "etl/steps/data/garden/excess_mortality/latest/hmd_stmf.py", line 142, in add_uk
      assert (
AssertionError: Too many missing values. Check values in year columns!
```

We ran into it because [STMF stopped publishing data](https://www.mortality.org/Data/STMF) for the UK, and we're leaping into the new year.

I've increased the tolerance for missing values as a hotfix before we fix it properly.

**Comment by lucasrodes** [comment]
There is no 2024 data for several countries. I have contacted HMD to see if they plan to release 2024 data.
