### ISSUE TITLE
`etl-staging-sync` fails if `--staging-created-at` is not passed

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2187]
When running `etl-staging-sync`, it seems that an error is raised unless the argument `--staging-creatd-at` is passed.

At least that's what I have experienced a few times. For example, it's happening now when running:
```
etl-staging-sync add-nuclear-weapons-proliferation-data .env.live --dry-run
```

The full error is:
```
2024-01-15 12:46:40,472 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/bin/etl-staging-sync", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 119, in cli
    staging_created_at = _get_git_branch_creation_date(str(source).replace("staging-site-", ""))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 408, in _get_git_branch_creation_date
    raise ValueError(f"Could not find branch {branch_name}, use --staging-created-at to specify it manually")
ValueError: Could not find branch add-nuclear-weapons-proliferation-data, use --staging-created-at to specify it manually
```

**Comment by pabloarosado** [comment]
I just realized the problem: The git branch needs to exist locally for the `etl-staging-sync` script to work. My workflow is usually to merge the branch to master, then delete the local branch, and then run this script. So, I guess that:
1. Ideally, the script would not rely on the local git and instead fetch the required data from the remote repos (and if that's not possible, the script could fetch the branch temporarily and then delete it).
2. If that's somehow not possible, maybe the error could be excepted and a message would then say that the branch needs to be fetched locally, or otherwise the argument `--staging-created-at` is required.

**Comment by Marigold** [comment]
Fixed [here](https://github.com/owid/etl/commit/12396b9b6ca93b84dd6b6125969f415d26e2b040). I used an unnecessarily complex way of getting the PR creation date. I switched to Github API, which is much simpler.
