### ISSUE TITLE
🐛 dummy datasets not being loaded

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2286]
I get an `KeyError: 'title'` error when trying to load the table of any of the dummy datasets:

First part works:

```python
from owid.catalog import Dataset
from etl.paths import DATA_DIR

path = DATA_DIR / "meadow/dummy/2020-01-01/dummy"

dataset = Dataset(path)
```

Then it breaks when trying to get its table:

```python
# Error raised when trying to access its table
tb = dataset["dummy"]

```

The same happens with `meadow/dummy/2020-01-01/dummy_full`

**Full error traceback:**
```
Traceback (most recent call last):
  File "~/repos/etl/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "~/repos/etl/apps/wizard/pages/harmonizer.py", line 141, in <module>
    tb = dataset[table_name].reset_index()
  File "~/repos/etl/lib/catalog/owid/catalog/datasets.py", line 153, in __getitem__
    t = tables.Table.read(path)
  File "~/repos/etl/lib/catalog/owid/catalog/tables.py", line 172, in read
    table = cls.read_feather(path)
  File "~/repos/etl/lib/catalog/owid/catalog/tables.py", line 355, in read_feather
    cls._add_metadata(df, path)
  File "~/repos/etl/lib/catalog/owid/catalog/tables.py", line 334, in _add_metadata
    df._set_fields_from_dict(fields)
  File "~/repos/etl/lib/catalog/owid/catalog/tables.py", line 380, in _set_fields_from_dict
    self._fields = defaultdict(VariableMeta, {k: VariableMeta.from_dict(v) for k, v in fields.items()})
  File "~/repos/etl/lib/catalog/owid/catalog/tables.py", line 380, in <dictcomp>
    self._fields = defaultdict(VariableMeta, {k: VariableMeta.from_dict(v) for k, v in fields.items()})
  File "~/repos/etl/.venv/lib/python3.10/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "~/repos/etl/.venv/lib/python3.10/site-packages/dataclasses_json/core.py", line 210, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "~/repos/etl/.venv/lib/python3.10/site-packages/dataclasses_json/core.py", line 275, in _decode_generic
    res = _get_type_cons(type_)(xs)
  File "~/repos/etl/.venv/lib/python3.10/site-packages/dataclasses_json/core.py", line 334, in <genexpr>
    items = (_decode_dataclass(type_arg, x, infer_missing)
  File "~/repos/etl/.venv/lib/python3.10/site-packages/dataclasses_json/core.py", line 168, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'title'
```

**Comment by Marigold** [comment]
I can't replicate it with your snippet. Could you try

1. `rm -rf data/meadow/dummy/2020-01-01/dummy`
2. `etl dummy`

and then try again?

**Comment by lucasrodes** [comment]
That worked, thanks Mojmir!
