### ISSUE TITLE
Chart sync tool requires staging-created-at argument

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2451]
The chart sync tool in the wizard fails with an error that sounds as if the branch you are trying to sync did not exist. However, the real issue seems to be that the argument `staging-created-at` is required.

The workaround is to use the cli and pass that argument.

So I suppose that, either there is some bug in the backend (and the staging-created-at argument is not really necessary), or the wizard should ask the user to manually input that date before executing the chart sync.

This is the error I was getting now when trying to sync `update-faostat-data` to live:

```
2024-03-25 16:47:55,655 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in call
    return self.main(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
    ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 124, in cli
    staging_created_at = _get_staging_created_at(source, staging_created_at)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 284, in _get_staging_created_at
    return _get_git_branch_creation_date(str(source).replace("staging-site-", ""))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 396, in _get_git_branch_creation_date
    assert len(js) == 1, f"Branch {branch_name} not found in owid/etl repository"
    ^^^^^^^^^^^^
AssertionError: Branch update-faostat-data not found in owid/etl repository
```

**Comment by Marigold** [comment]
It was caused by multiple closed branches.
