### ISSUE TITLE
Chart sync fails because of missing `isPublished`

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2452]
When running `etl chart-sync update-faostat-data .env.live --staging-created-at 2024-03-14 --dry-run`, I get a `KeyError`.

<details><summary>Full log:</summary>
(etl-py3.11) ➜  etl git:(master) etl chart-sync update-faostat-data .env.live --staging-created-at 2024-03-20 --dry-run
2024-03-25 17:49:31 [info     ] staging_sync.start             chart_ids={1024, 1025, 1538, 1027, 1029, 1030, 1031, 7685, 5129, 1035, 525, 1037, 1038, 1039, 1040, 2576, 5138, 533, 534, 1046, 1559, 1562, 2086, 4652, 4653, 558, 1070, 1072, 1073, 571, 4156, 1088, 1089, 1090, 4675, 4676, 4677, 4678, 4679, 4680, 4681, 6216, 589, 590, 3676, 1127, 3175, 3176, 2673, 1149, 1154, 5624, 5116, 5625, 5626, 2713, 3738, 3236, 4774, 6550, 715, 2766, 4823, 2777, 2778, 2779, 2780, 2782, 2784, 1249, 1250, 2785, 2786, 2787, 2788, 743, 2789, 745, 746, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 4848, 768, 787, 5348, 802, 823, 826, 5949, 4926, 841, 6989, 847, 848, 852, 853, 855, 856, 863, 864, 6500, 872, 4970, 4971, 4973, 878, 4974, 881, 886, 888, 3961, 3450, 891, 893, 5503, 4992, 3970, 3971, 4995, 5508, 3974, 5509, 3977, 3978, 3979, 3980, 3981, 3982, 3984, 1940, 1941, 1942, 1943, 1944, 3993, 1946, 3994, 1948, 1949, 3995, 3996, 3999, 4000, 4001, 4002, 4003, 4004, 4005, 4006, 4007, 4008, 4010, 939, 4011, 4012, 4013, 4014, 4015, 4016, 4017, 5550, 949, 951, 4539, 7108, 7110, 974, 975, 5584, 5075, 980, 3032, 3033, 4589, 4590, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1022, 1023} n=192
2024-03-25 17:49:32 [info     ] staging_sync.create_chart_revision chart_id=1024 slug=pig-yields-meat-per-animal-in-hectograms-100-grams
2024-03-25 17:49:32 [info     ] staging_sync.create_chart_revision chart_id=1025 slug=cattle-meat-yields-hectograms-100-grams-per-animal
2024-03-25 17:49:34 [info     ] staging_sync.create_chart_revision chart_id=1538 slug=global-change-over-the-last-50-years
2024-03-25 17:49:35 [info     ] staging_sync.create_chart_revision chart_id=1027 slug=cereal-distribution-to-uses
2024-03-25 17:49:35 [info     ] staging_sync.create_chart_revision chart_id=1029 slug=seafood-and-fish-production-thousand-tonnes
2024-03-25 17:49:36 [info     ] staging_sync.create_chart_revision chart_id=1030 slug=per-capita-meat-consumption-by-type-kilograms-per-year
2024-03-25 17:49:36 [info     ] staging_sync.create_chart_revision chart_id=1031 slug=per-capita-milk-consumption
2024-03-25 17:49:37,401 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/bin/etl", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 262, in cli
    assert target_chart.config["isPublished"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'isPublished'
</details>

**Comment by Marigold** [comment]
The problematic chart isn't published, but it went through chart approval once. Excluded such edge cases.
