### ISSUE TITLE
Chart sync tool in wizard fails when syncing local to staging grapher

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2473]
When syncing the wizard chart sync tool, Source: `.env`, Target: `update-agriculture-data` (or any other staging branch), I get the following error:

```
2024-03-29 13:17:51,564 - [bugsnag] WARNING - No API key configured, couldn't notify Traceback (most recent call last): File "<string>", line 1, in <module> File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in call return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 124, in cli staging_created_at = _get_staging_created_at(source, staging_created_at) # type: ignore ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 284, in _get_staging_created_at return _get_git_branch_creation_date(str(source).replace("staging-site-", "")) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 399, in _get_git_branch_creation_date assert len(js) > 0, f"Branch {branch_name} not found in owid/etl repository" ^^^^^^^^^^^ AssertionError: Branch .env not found in owid/etl repository
```

I see that, when running the command `etl chart-sync .env update-agriculture-data --dry-run`, I get the error `Invalid value: staging-created-at is required when source is not a staging server name` (and the command works when I pass argument `staging-created-at`). So this issue may be related to https://github.com/owid/etl/issues/2451

**Comment by Marigold** [comment]
That's expected. chart-sync uses `staging-created-at` (time when the branch was created) and checks if there were any updates in live (target) after that time. If you work with `.env`, there's no branch creation time, and you have to pass it yourself. It could be pretty much any time, especially if you're only adding charts.

**Comment by pabloarosado** [comment]
That makes sense. It would be useful if the wizard was adapted to the case when the user passes two env files (currently, only the cli can handle that case).

**Comment by Marigold** [comment]
I'll use reasonable default for staging-created-at or add a field in wizard.

**Comment by Marigold** [comment]
I didn't notice this part of the error
```
AssertionError: Branch .env not found in owid/etl repository
```
this means you were trying to use `.env` local file, but it didn't exist and chart sync thought it is a branch name. I'm raising error about missing file now.

I've also added default of 1 week for staging-created-at (meaning that you'd get warnings if someone edited a chart in production in that 1 week window).
