### ISSUE TITLE
Snapshot: Getting an error when uploading a local file

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#2499]
I'm getting this error when I try and upload a local csv to snapshot. I'll try it with a simple test csv to check it is not the csv that is problematic.

> .venv) fionaspooner@Fionas-MBP etl % python snapshots/who/2024-04-08/polio_afp.py
> Path to file: /Users/fionaspooner/Desktop/who_afp.csv
> 2024-04-08 16:09:23,799 - [bugsnag] WARNING - No API key configured, couldn't notify
> WARNING:bugsnag:No API key configured, couldn't notify
> Traceback (most recent call last):
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/snapshots/who/2024-04-08/polio_afp.py", line 25, in <module>
>     main()
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/snapshots/who/2024-04-08/polio_afp.py", line 21, in main
>     snap.create_snapshot(filename=path_to_file, upload=upload)
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/etl/snapshot.py", line 175, in create_snapshot
>     add_snapshot(uri=self.uri, filename=filename, dataframe=data, upload=upload)
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/etl/snapshot.py", line 541, in add_snapshot
>     snap.dvc_add(upload=upload)
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/etl/snapshot.py", line 159, in dvc_add
>     meta = ruamel_load(f)
>            ^^^^^^^^^^^^^^
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/etl/files.py", line 197, in ruamel_load
>     return ruamel.yaml.load(f, Loader=ruamel.yaml.RoundTripLoader, preserve_quotes=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/.venv/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1085, in load
>     error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
>   File "/Users/fionaspooner/Documents/OWID/repos/etl/.venv/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
>     raise AttributeError(s, name=None)
> AttributeError: 
> "load()" has been removed, use
> 
>   yaml = YAML(typ='rt')
>   yaml.load(...)
> 
> and register any classes that you use, or check the tag attribute on the loaded data,
> instead of file "/Users/fionaspooner/Documents/OWID/repos/etl/etl/files.py", line 197
> 
>     return ruamel.yaml.load(f, Loader=ruamel.yaml.RoundTripLoader, preserve_quotes=True)

**Comment by spoonerf** [comment]
Yep it is still a problem when I try with a very simple csv

**Comment by spoonerf** [comment]
Fixed in #2500
