### ISSUE TITLE
Checksum mismatch on backported data causes ETL failure

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#252]
Running the ETL locally on my machine:

```
Running 124 steps:
1. backport://backport/owid/latest/dataset_70_population__gapminder__hyde__and__un...
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/etl", line 5, in <module>
    main()
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 81, in main
    run_dag(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 143, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 150, in timed_run
    f()
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 143, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/steps/__init__.py", line 649, in run
    dataset = backport_helpers.create_dataset(
  File "/Users/lars/Documents/owid/etl/etl/backport_helpers.py", line 80, in create_dataset
    values = load_values(short_name)
  File "/Users/lars/Documents/owid/etl/etl/backport_helpers.py", line 21, in load_values
    local_path = walden_ds.ensure_downloaded()
  File "/Users/lars/Documents/owid/etl/vendor/walden/owid/walden/catalog.py", line 196, in ensure_downloaded
    files.download(url, filename, expected_md5=self.md5, quiet=quiet)
  File "/Users/lars/Documents/owid/etl/vendor/walden/owid/walden/files.py", line 88, in download
    raise ChecksumDoesNotMatch(f"for file downloaded from {url}")
owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_70_population__gapminder__hyde__and__un_values.feather
```

**Comment by larsyencken** [comment]
The file at `s3://walden/backport/latest/dataset_70_population__gapminder__hyde__and__un_values.feather` has md5 `08a2781daf773a397bb839f208ca24b3`, but the walden config indicates it should have md5 `f4bf438a89deb7d0556d89e7160b6455`.

**Comment by larsyencken** [comment]
(for next week) @Marigold any ideas what might have happened?

**Comment by Marigold** [comment]
This was my fault, I was profiling in staging environment and accidentally pushed files to walden without committing changes to the repository. I'll think what could be done to prevent this (= my stupidity) in the future.
