### ISSUE TITLE
ETL fails for food explorer due to too many open files

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#253]
Got this on M1 MacOS 12.4 (Monterey), after trying to rebuild the ETL on latest `master`:

```
2. data://garden/explorers/2021/food_explorer...
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/nbclient/client.py", line 602, in setup_kernel
    yield
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/papermill/clientwrap.py", line 45, in execute
    self.papermill_execute_cells()
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/nbclient/util.py", line 48, in just_run
    loop = asyncio.new_event_loop()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/selector_events.py", line 61, in __init__
    self._make_self_pipe()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/selector_events.py", line 108, in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/socket.py", line 606, in socketpair
    a, b = _socket.socketpair(family, type, proto)
OSError: [Errno 24] Too many open files
```

**Comment by larsyencken** [comment]
@pabloarosado Something to check out for next week.

**Comment by pabloarosado** [comment]
Hi @larsyencken , [this PR](https://github.com/owid/etl/pull/245) by @Marigold should fix that issue. For the time being before merging it, the workaround is to do `ulimit -n 4096` before executing the food explorer step.

**Comment by Marigold** [comment]
@pabloarosado thanks for chiming in, you're right. I've just merged that PR and closing this.
