### ISSUE TITLE
Chart-sync fails when syncing from local to staging

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2533]
When trying to sync local grapher to a staging server (branch `update-climate-data-and-fix-co2-concentration-issue`), I get an issue, both when using the wizard and the cli. I haven't looked into it but the issue may be caused by unrelated work (about natural disasters, that is dealt with in another branch).

For now I give up on syncing from local to staging, and will simply redo chart revisions on staging. But I created the issue for the record.

```
(etl-py3.11) ➜  etl git:(update-climate-data-and-fix-co2-concentration-issue) etl chart-sync .env update-climate-data-and-fix-co2-concentration-issu --staging-created-at 2024-04-16 --dry-run
2024-04-17 12:57:25 [info     ] staging_sync.start             chart_ids={7174, 3207, 7175, 7568, 7569, 7570, 7571, 7572, 7573, 7574, 7575, 7576, 7577, 7578, 7579, 7580, 7581, 7582, 7583, 7584, 7585, 7586, 5421, 5427, 5428, 1850, 1851, 1853, 730, 731, 732, 2912, 1777, 1525} n=34
2024-04-17 12:57:25,872 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/etl/grapher_model.py", line 357, in migrate_to_db
    target_var = Variable.load_from_catalog_path(target_session, source_var.catalogPath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/etl/grapher_model.py", line 1245, in load_from_catalog_path
    return session.exec(select(cls).where(cls.catalogPath == catalog_path)).one()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1522, in one
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 148, in cli
    target_chart = source_chart.migrate_to_db(source_session, target_session)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/etl/grapher_model.py", line 359, in migrate_to_db
    raise ValueError(f"variables.catalogPath not found in target: {source_var.catalogPath}")
ValueError: variables.catalogPath not found in target: grapher/emdat/2024-04-11/natural_disasters/natural_disasters_yearly#total_damages_per_gdp_drought_yearly

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/bin/etl", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prosado/Documents/owid/repos/etl/apps/staging_sync/cli.py", line 151, in cli
    raise ValueError("ETL deploy hasn't finished yet. Check the repository.") from e
ValueError: ETL deploy hasn't finished yet. Check the repository.
```

**Comment by Marigold** [comment]
@pabloarosado you're right that it's caused by unrelated work - natural disasters. This is the important part from the traceback
```
ValueError: variables.catalogPath not found in target: grapher/emdat/2024-04-11/natural_disasters/natural_disasters_yearly#total_damages_per_gdp_drought_yearly
```
The thing is that `etl chart-sync` tries to sync **all your local charts** to target (it was meant primarily for staging servers). We could add an `--include` and `--exclude` there so that you can only filter variables that you care about. Would that be helpful?

**Comment by pabloarosado** [comment]
Thanks @Marigold, I understand the problem, and I suppose it's a new reason to avoid working in local grapher, and to rather work on staging servers. I suppose the include/exclude options would be helpful, but not sure if it's worth it.

**Comment by pabloarosado** [comment]
@Marigold actually, now I'm back to natural disasters data, and now I definitely need the chart sync tool (I did many changes in local grapher), but I'm still getting the same error. Any idea of the reason, or a workaround? Thanks!
