### ISSUE TITLE
bug: clean installation not working

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2539]
I just cloned the repository and I am trying to install the project following [our guidelines](https://docs.owid.io/projects/etl/getting-started/working-environment/#install-dependencies). 

When running `make test` I get an error related to MySQL Client. If I run `poetry install`, same happens. Error below:

```
~ poetry install                         
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing mysqlclient (2.2.3): Failed

  CalledProcessError

  Command '['/Users/lucasrodes/repos/etl/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/lucasrodes/repos/etl/.venv', '--no-deps', '/Users/lucasrodes/Library/Caches/pypoetry/artifacts/8d/06/6e/1c5b3b4e470b853206aefe7e516af70e90a9a7bc819ee8495ab1257bea/mysqlclient-2.2.3.tar.gz']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.11.1/lib/python3.11/subprocess.py:571 in run
       567│             # We don't call process.wait() as .__exit__ does that for us.
       568│             raise
       569│         retcode = process.poll()
       570│         if check and retcode:
    →  571│             raise CalledProcessError(retcode, process.args,
       572│                                      output=stdout, stderr=stderr)
       573│     return CompletedProcess(process.args, retcode, stdout, stderr)
       574│ 
       575│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/lucasrodes/repos/etl/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/lucasrodes/repos/etl/.venv', '--no-deps', '/Users/lucasrodes/Library/Caches/pypoetry/artifacts/8d/06/6e/1c5b3b4e470b853206aefe7e516af70e90a9a7bc819ee8495ab1257bea/mysqlclient-2.2.3.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/lucasrodes/Library/Caches/pypoetry/artifacts/8d/06/6e/1c5b3b4e470b853206aefe7e516af70e90a9a7bc819ee8495ab1257bea/mysqlclient-2.2.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [30 lines of output]
        /bin/sh: pkg-config: command not found
        /bin/sh: pkg-config: command not found
        /bin/sh: pkg-config: command not found
        Trying pkg-config --exists mysqlclient
        Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
        Trying pkg-config --exists mariadb
        Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
        Trying pkg-config --exists libmariadb
        Command 'pkg-config --exists libmariadb' returned non-zero exit status 127.
        Traceback (most recent call last):
          File "/Users/lucasrodes/repos/etl/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
            main()
          File "/Users/lucasrodes/repos/etl/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/Users/lucasrodes/repos/etl/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/gd/59pzvyv54g1_2y72h60y6s_00000gn/T/pip-build-env-2c8jjapz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/gd/59pzvyv54g1_2y72h60y6s_00000gn/T/pip-build-env-2c8jjapz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
            self.run_setup()
          File "/private/var/folders/gd/59pzvyv54g1_2y72h60y6s_00000gn/T/pip-build-env-2c8jjapz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
            exec(code, locals())
          File "<string>", line 155, in <module>
          File "<string>", line 49, in get_config_posix
          File "<string>", line 28, in find_package_name
        Exception: Can not find valid pkg-config name.
        Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  

  at ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /Users/lucasrodes/Library/Caches/pypoetry/artifacts/8d/06/6e/1c5b3b4e470b853206aefe7e516af70e90a9a7bc819ee8495ab1257bea/mysqlclient-2.2.3.tar.gz

  at ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│
```

**Comment by Marigold** [comment]
Does install `pkg-config` with `brew install pkg-config` or `sudo apt-get install pkg-config` works?

**Comment by lucasrodes** [comment]
Should have been fixed by https://github.com/owid/etl/pull/2557/files
