### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2709]
When running `make check` I get the following error:

```
✗ make check
==> Lint & Format & Typecheck changed files
13 files left unchanged
WARNING: there is a new pyright version available (v1.1.288 -> v1.1.365).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

/usr/lib/node_modules/npm/lib/es6/validate-engines.js:31
    throw err
    ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-collect/index.js:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/cacache/lib/get.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)

Node.js v21.6.2
make: *** [default.mk:28: check-default] Error 123
```

This is the second time that this error occurs to me. Last time it disappeared, so I ignored it. Might be to some change in node dependencies?

**Comment by Marigold** [comment]
Do you use [nvm](https://github.com/nvm-sh/nvm) to manage your node versions? (it's like pyenv for node) It's possible that your system node versions got updated and hence you started getting this error. Unfortunately, our pyright version is quite old and cannot be easily updated (we'd have to fix 100+ files) and might not support the most recent node versions.

Could you run `which node` and `which pyright` to diagnose it?

**Comment by lucasrodes** [comment]
```
~ which node
/home/lucas/.nvm/versions/node/v18.20.2/bin/node
~  etl git:(fix/wizard-3) ✗ which pyright
/home/lucas/repos/etl/.venv/bin/pyright
```

It is working now though!

**Comment by Marigold** [comment]
All paths look good. I guess you must have been in a different environment somehow.

**Comment by lucasrodes** [comment]
This was solved on my end by using latest node version:

```
nvm use 22
```
