### ISSUE TITLE
`garden/who/2024-05-20/vehicles` step fails finding `population`

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#3030]
We get an error running a garden step in `master`:

```
--- Detecting which steps need rebuilding...
OK (5.6s)
--- Running 2 steps (at least 6.1s):
--- 1. data://garden/who/2024-05-20/vehicles (3.8s)
2024-07-29 09:57:15,085 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 33, in main
    _import_and_run(path, dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 53, in _import_and_run
    module.run(dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/who/2024-05-20/vehicles.py", line 17, in run
    table = make_table()
            ^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/who/2024-05-20/vehicles.py", line 39, in make_table
    table_population = load_key_indicators()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/who/2024-05-20/vehicles.py", line 54, in load_key_indicators
    population = population[["country", "year", "population"]]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 4096, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['population'] not in index"

COMMAND: poetry run etl d run-python-step data://garden/who/2024-05-20/vehicles /Users/lars/Documents/owid/etl/data/garden/who/2024-05-20/vehicles
```

It appears that it is using `catalog.find_latest()` to get `population` data, instead of fetching a specific version, or getting it via dependencies.

**Comment by larsyencken** [comment]
Ignore me, already fixed here: https://github.com/owid/etl/pull/3006
