### ISSUE TITLE
Nightly build fails on multiple steps

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#3031]
We have failures over multiple days on the nightly build: https://buildkite.com/our-world-in-data/etl-full-private-rebuild-nightly

Several steps appear to be failing.

### `garden/harvard/2023-09-18/colonial_dates_dataset`

<details><summary>Traceback</summary>

```
bk;t=1722213749841^GTraceback (most recent call last):
bk;t=1722213749841^G  File "<string>", line 1, in <module>
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in __call__
bk;t=1722213749841^G    return super().__call__(*args, **kwargs)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
bk;t=1722213749841^G    return self.main(*args, **kwargs)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
bk;t=1722213749841^G    rv = self.invoke(ctx)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
bk;t=1722213749841^G    return _process_result(sub_ctx.command.invoke(sub_ctx))
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
bk;t=1722213749841^G    return _process_result(sub_ctx.command.invoke(sub_ctx))
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
bk;t=1722213749841^G    return ctx.invoke(self.callback, **ctx.params)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
bk;t=1722213749841^G    return __callback(*args, **kwargs)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/run_python_step.py", line 33, in main
bk;t=1722213749841^G    _import_and_run(path, dest_dir)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/run_python_step.py", line 53, in _import_and_run
bk;t=1722213749841^G    module.run(dest_dir)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/steps/data/garden/harvard/2023-09-18/colonial_dates_dataset.py", line 34, in run
bk;t=1722213749841^G    tb = process_data(tb, tb_pop)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/steps/data/garden/harvard/2023-09-18/colonial_dates_dataset.py", line 87, in process_data
bk;t=1722213749841^G    tb_colonized["year"] = tb_colonized.apply(lambda x: list(range(x["colstart_max"], x["colend_max"] + 1)), axis=1)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/lib/catalog/owid/catalog/tables.py", line 389, in __setitem__
bk;t=1722213749841^G    super().__setitem__(key, value)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4289, in __setitem__
bk;t=1722213749841^G    self._set_item_frame_value(key, value)
bk;t=1722213749841^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4447, in _set_item_frame_value
bk;t=1722213749841^G    raise ValueError(
bk;t=1722213749841^GValueError: Cannot set a DataFrame with multiple columns to the single column year
```
</details>

### `garden/health/2023-08-16/deaths_karlinsky`

<details><summary>Traceback</summary>

```
bk;t=1722213777920^GTraceback (most recent call last):
bk;t=1722213777920^G  File "<string>", line 1, in <module>
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in __call__
bk;t=1722213777920^G    return super().__call__(*args, **kwargs)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
bk;t=1722213777920^G    return self.main(*args, **kwargs)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
bk;t=1722213777920^G    rv = self.invoke(ctx)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
bk;t=1722213777920^G    return _process_result(sub_ctx.command.invoke(sub_ctx))
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
bk;t=1722213777920^G    return _process_result(sub_ctx.command.invoke(sub_ctx))
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
bk;t=1722213777920^G    return ctx.invoke(self.callback, **ctx.params)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
bk;t=1722213777920^G    return __callback(*args, **kwargs)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/run_python_step.py", line 33, in main
bk;t=1722213777920^G    _import_and_run(path, dest_dir)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/run_python_step.py", line 53, in _import_and_run
bk;t=1722213777920^G    module.run(dest_dir)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/steps/data/garden/health/2023-08-16/deaths_karlinsky.py", line 39, in run
bk;t=1722213777920^G    _sanity_checks(tb)
bk;t=1722213777920^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/steps/data/garden/health/2023-08-16/deaths_karlinsky.py", line 74, in _sanity_checks
bk;t=1722213777921^G    tb_ = geo.add_population_to_dataframe(tb_)
bk;t=1722213777921^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/data_helpers/geo.py", line 605, in add_population_to_dataframe
bk;t=1722213777921^G    population = _load_population()
bk;t=1722213777921^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/etl/data_helpers/geo.py", line 79, in _load_population
bk;t=1722213777921^G    population = Dataset(DATASET_POPULATION)[TNAME_KEY_INDICATORS]
bk;t=1722213777921^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/lib/catalog/owid/catalog/datasets.py", line 66, in __init__
bk;t=1722213777921^G    self.metadata = DatasetMeta.load(self._index_file)
bk;t=1722213777921^G  File "/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/lib/catalog/owid/catalog/meta.py", line 70, in load
bk;t=1722213777921^G    with open(filename) as istream:
bk;t=1722213777921^GFileNotFoundError: [Errno 2] No such file or directory: '/var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/data/garden/owid/latest/key_indicators/index.json'
bk;t=1722213778191^G
bk;t=1722213778191^GCOMMAND: prlimit --as=34359738368 poetry run etl d run-python-step data://garden/health/2023-08-16/deaths_karlinsky /var/lib/buildkite-agent/builds/etl-build-2-18/our-world-in-data/etl-full-private-rebuild-nightly/data/garden/health/2023-08-16/deaths_karlinsky
```
</details>

**Comment by Marigold** [comment]
The second one is handled in https://github.com/owid/etl/pull/3028. I'll look into the first one.

**Comment by Marigold** [comment]
Our nightly has been stable for a while.
