### ISSUE TITLE
Failing backport: backport://backport/owid/latest/dataset_1002

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#305]
Getting an `InvalidArrowFile` for one of the backports when I try to run it locally:

```
1. backport://backport/owid/latest/dataset_1002_incidence_of_managerial_or_professional_jobs_and_collective_bargaining_by_gender__blau_and_kahn__2017...
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/etl", line 5, in <module>
    main_cli()
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 77, in main_cli
    return main(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 116, in main
    run_dag(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 200, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 207, in timed_run
    f()
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 200, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/steps/__init__.py", line 676, in run
    dataset = backport_helpers.create_dataset(
  File "/Users/lars/Documents/owid/etl/etl/backport_helpers.py", line 84, in create_dataset
    values = values_future.result()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/lars/Documents/owid/etl/etl/backport_helpers.py", line 22, in load_values
    return cast(pd.DataFrame, pd.read_feather(local_path))
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pandas/io/feather_format.py", line 132, in read_feather
    return feather.read_feather(
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pyarrow/feather.py", line 220, in read_feather
    return (read_table(
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pyarrow/feather.py", line 244, in read_table
    reader = _feather.FeatherReader(
  File "pyarrow/_feather.pyx", line 79, in pyarrow._feather.FeatherReader.__cinit__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: File is too small to be a well-formed file
```

**Comment by Marigold** [comment]
Can you please try cleaning up walden cache (and perhaps `data/backport` too)? i.e. `rm -Rf ~/.owid/walden/backport`

(I remember seeing this error a while ago, that dataset 1002 is from the early backport days.)
