### ISSUE TITLE
Error: a type extension with name pandas.period already defined

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#333]
Getting this transient error for multiple FAO steps. It disappears if you run the step for a second time.

```
4. data://garden/faostat/2022-05-17/faostat_qcl...
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/etl", line 5, in <module>
    main_cli()
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 77, in main_cli
    return main(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 116, in main
    run_dag(
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 200, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 207, in timed_run
    f()
  File "/Users/lars/Documents/owid/etl/etl/command.py", line 200, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/Users/lars/Documents/owid/etl/etl/steps/__init__.py", line 279, in run
    self._run_py()
  File "/Users/lars/Documents/owid/etl/etl/steps/__init__.py", line 380, in _run_py
    step_module.run(self._dest_dir.as_posix())  # type: ignore
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/faostat/2022-05-17/faostat_qcl.py", line 341, in run
    data_table_meadow = dataset_meadow[dataset_short_name]
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/datasets.py", line 94, in __getitem__
    return tables.Table.read_feather(table_filename)
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/tables.py", line 198, in read_feather
    df = Table(pd.read_feather(path))
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pandas/io/feather_format.py", line 132, in read_feather
    return feather.read_feather(
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pyarrow/feather.py", line 220, in read_feather
    return (read_table(
  File "pyarrow/array.pxi", line 767, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 1996, in pyarrow.lib.Table._to_pandas
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pyarrow/pandas_compat.py", line 789, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pyarrow/pandas_compat.py", line 1137, in _table_to_blocks
    return [_reconstruct_block(item, columns, extension_columns)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pyarrow/pandas_compat.py", line 1137, in <listcomp>
    return [_reconstruct_block(item, columns, extension_columns)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pyarrow/pandas_compat.py", line 749, in _reconstruct_block
    pd_ext_arr = pandas_dtype.__from_arrow__(arr)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pandas/core/arrays/numeric.py", line 47, in __from_arrow__
    from pandas.core.arrays._arrow_utils import pyarrow_array_to_numpy_and_mask
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/pandas/core/arrays/_arrow_utils.py", line 85, in <module>
    pyarrow.register_extension_type(_period_type)
  File "pyarrow/types.pxi", line 963, in pyarrow.lib.register_extension_type
  File "pyarrow/error.pxi", line 118, in pyarrow.lib.check_status
pyarrow.lib.ArrowKeyError: A type extension with name pandas.period already defined
```

**Comment by larsyencken** [comment]
@Marigold Hit this a few times this morning. Reckon it's an isolation issue, or something else?

**Comment by Marigold** [comment]
It's likely an isolation issue. I hotfixed it [yesterday in the evening](https://github.com/owid/etl/commit/0947512768ebae41a8581840522a533d6f731cb8) by keeping some modules imported. We didn't get errors from prod since then.
