### ISSUE TITLE
Error: fasttrack not running any steps

### ISSUE THREAD

**Issue by Marigold** [owid/etl#334]
Getting this from fasttrack. I'll have to dig deeper to find why is it not executing any steps and if that's a problem or not.
```
Traceback (most recent call last):
 File "/home/owid/etl/.venv/bin/fasttrack", line 5, in <module>
 fasttrack()
 File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
 return self.main(*args, **kwargs)
 File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
 rv = self.invoke(ctx)
 File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
 return ctx.invoke(self.callback, **ctx.params)
 File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
 return __callback(*args, **kwargs)
 File "/home/owid/etl/backport/fasttrack.py", line 83, in fasttrack
 etl(
 File "/home/owid/etl/etl/command.py", line 116, in main
 run_dag(
 File "/home/owid/etl/etl/command.py", line 184, in run_dag
 raise ValueError(
ValueError: No steps matched the given input. Check spelling or consult `etl --help` for more options
```

**Comment by Marigold** [comment]
Adding better logging and waiting for the next error, seems to happen for a relatively small group of datasets.
