### ISSUE TITLE
Error: too many open files

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#338]
Trying to do `etl garden`, I got this too many open files error suddenly. I'm on an M1 MacOS machine.

```
18. data://garden/faostat/2021-06-17/faostat_rl...
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/nbclient/util.py", line 48, in just_run
    loop = asyncio.new_event_loop()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/selector_events.py", line 61, in __init__
    self._make_self_pipe()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/asyncio/selector_events.py", line 108, in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
  File "/Users/lars/.pyenv/versions/3.9.7/lib/python3.9/socket.py", line 606, in socketpair
    a, b = _socket.socketpair(family, type, proto)
OSError: [Errno 24] Too many open files
```

**Comment by larsyencken** [comment]
I can check how many open file descriptors are allowed with `ulimit -n`. The default on MacOS is 256. Reading more, it seems like modern machines can safely set this much much higher.

I added `ulimit -n 10000` to my `~/.zshrc` file at the end, increasing the limit by default for me.

Closing this issue now unless it comes up again.

**Comment by Marigold** [comment]
We've encountered [this before](https://owid.slack.com/archives/C02K1BAUCA2/p1655894440381619?thread_ts=1655891775.513559&cid=C02K1BAUCA2). Shouldn't we show a warning or set it from python process with something like `resource.setrlimit(resource.RLIMIT_NOFILE, (15000, resource.getrlimit(resource.RLIMIT_NOFILE)[1]))`? (Not sure if it's possible to manipulate resource limits from within python)

**Comment by larsyencken** [comment]
Good call, I PR'd your fix now
