### ISSUE TITLE
Failing food explorer: boolean value of NA is ambiguous

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#345]
```
(.venv) lars@juniper owid/etl (master) » time etl --private --backport                                                                                                   1 ↵
Detecting which steps need rebuilding...
Running 1 steps:
1. data://explorers/owid/latest/food_explorer...
  0%|                                                                                                                                                | 0/190 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/run_python_step", line 5, in <module>
    main()
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 25, in main
    _import_and_run(path, dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 43, in _import_and_run
    module.run(dest_dir)  # type: ignore
  File "/Users/lars/Documents/owid/etl/etl/steps/data/explorers/owid/latest/food_explorer.py", line 97, in run
    dataset.add(table_product, formats=["csv", "feather", "parquet"])
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/datasets.py", line 93, in add
    table.to_feather(table_filename, repack=repack)
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/tables.py", line 113, in to_feather
    df = repack_frame(df)
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/frames.py", line 40, in repack_frame
    [
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/frames.py", line 41, in <listcomp>
    repack_series(df[col]) if col not in dtypes else df[col]
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/frames.py", line 70, in repack_series
    return shrink_integer(s)
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/frames.py", line 100, in shrink_integer
    if s.min() < 0:
  File "pandas/_libs/missing.pyx", line 382, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous
```

**Comment by larsyencken** [comment]
It's due to this line:

```
  File "/Users/lars/Documents/owid/etl/etl/steps/data/explorers/owid/latest/food_explorer.py", line 97, in run
    dataset.add(table_product, formats=["csv", "feather", "parquet"])
```

I was experimenting also building the explorer files in other formats beyond CSV. I can hotfix it.
