### ISSUE TITLE
Error: etl failing after backported step got archived

### ISSUE THREAD

**Issue by Marigold** [owid/etl#349]
Running `etl dataset_5650 --private` fails at the moment because someone has archived `dataset_5650_statistical_review_of_world_energy__bp__2022` though we still have it [in DAG](https://github.com/owid/etl/blob/master/dag_files/dag_energy.yml#L15). @pabloarosado was it you by any chance?

We might also want a better error message, took me a while to figure this out.

**Comment by larsyencken** [comment]
This is also breaking the prod ETL at the moment.

```
1. backport://backport/owid/latest/dataset_5650_statistical_review_of_world_energy__bp__2022...
Traceback (most recent call last):
  File "/home/owid/etl/.venv/bin/etl", line 5, in <module>
    main_cli()
  File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/owid/etl/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/owid/etl/etl/command.py", line 77, in main_cli
    return main(
  File "/home/owid/etl/etl/command.py", line 116, in main
    run_dag(
  File "/home/owid/etl/etl/command.py", line 200, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/home/owid/etl/etl/command.py", line 207, in timed_run
    f()
  File "/home/owid/etl/etl/command.py", line 200, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/home/owid/etl/etl/steps/__init__.py", line 670, in run
    dataset = backport_helpers.create_dataset(
  File "/home/owid/etl/etl/backport_helpers.py", line 84, in create_dataset
    values = values_future.result()
  File "/home/owid/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/owid/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/owid/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/owid/etl/etl/backport_helpers.py", line 20, in load_values
    walden_ds = WALDEN_CATALOG.find_one(short_name=f"{short_name}_values")
  File "/home/owid/etl/vendor/walden/owid/walden/catalog.py", line 278, in find_one
    raise KeyError(f"no match for dataset {namespace}/{version}/{short_name}")
KeyError: 'no match for dataset None/None/dataset_5650_statistical_review_of_world_energy__bp__2022_values'
```

**Comment by pabloarosado** [comment]
Hi @Marigold yes I did that, I didn't think it would break things. Basically we don't need that dataset in grapher anymore (it's not used by any chart), but we still need the backported dataset. So this means that I should un-archive it?

**Comment by pabloarosado** [comment]
OK, I have un-achived [the dataset](https://owid.cloud/admin/datasets/5650) in live grapher.

**Comment by larsyencken** [comment]
Thanks Pablo!

**Comment by Marigold** [comment]
Thanks, I'll see if I can find time to improve the error.

**Comment by larsyencken** [comment]
Looks like this struck again today:

```
KeyError: 'no match for dataset None/None/dataset_5669_un_sdg__2022_07_07_values
```

**Comment by larsyencken** [comment]
I take it back, the dataset is not archived on prod, seems to be some other issue.

**Comment by larsyencken** [comment]
My issue turned out to be that I had switched Python version and not run `rm -rf .venv && poetry install` to refresh the virtual environment. That was leading to some wrong version of Walden getting used.
