### ISSUE TITLE
Jupyter notebooks can't be opened

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#351]
When I click on a jupyter notebook, I get the following error:
```bash
[E 09:34:32.413 NotebookApp] Uncaught exception GET /notebooks/etl_extra/AA_CHECK.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/etl_extra/AA_CHECK.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/tornado/gen.py", line 782, in run
        yielded = self.gen.send(value)
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 94, in get
        self.write(self.render_template('notebook.html',
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/notebook/base/handlers.py", line 511, in render_template
        return template.render(**ns)
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .html import HTMLExporter
      File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 11, in <module>
        from jinja2 import contextfilter
    ImportError: cannot import name 'contextfilter' from 'jinja2' (/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/jinja2/__init__.py)
[E 09:34:32.419 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Referer": "http://localhost:8888/tree/etl_extra",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
    }
[E 09:34:32.419 NotebookApp] 500 GET /notebooks/etl_extra/AA_CHECK.ipynb (::1) 56.580000ms referer=http://localhost:8888/tree/etl_extra
```
I have trashed the virtual environment and created it from scratch, and the error continues. However, this does not happen in other environments. For example, I have re-created the environment in walden from scratch, and this error does not happen.

**Comment by pabloarosado** [comment]
Hi @larsyencken I see that the latest change in the environment is [installing mistune](https://github.com/owid/etl/blame/master/pyproject.toml#L52). I have removed it from pyproject, and updated the poetry environment, and now jupyter works again. What is that package for? Thanks.

**Comment by larsyencken** [comment]
Ah, it came up as an existing dep that had a security flaw, nothing important for our use case, but I updated it. If that messed with Jupyter, we should totally undo that change.
