### ISSUE TITLE
Publish failing: cannot find module owid.catalog.helpers

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#352]
Getting this at the end of an `etl-prod.sh` run on `analytics:

```
Traceback (most recent call last):
  File "/home/owid/etl/.venv/bin/publish", line 2, in <module>
    from etl.publish import publish_cli
  File "/home/owid/etl/etl/publish.py", line 21, in <module>
    from owid.catalog.helpers import read_frame
ModuleNotFoundError: No module named 'owid.catalog.helpers'
```

**Comment by larsyencken** [comment]
My bad, hotfixed now
