### ISSUE TITLE
WDI garden step connects to grapher DB

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#442]
## Problem

- The general public can no longer build our `garden` dataset, since it requires a MySQL database for the WDI step for garden.
- Our `garden` build also became non-reproducible, since it is no longer a strict function of its inputs, but depends on whatever the contents of the grapher DB is
  - In general, even `grapher://` steps shouldn't use data from the DB as input to the dataset, they should only connect in order to do simple upserts of datasets

## Proposed solutions

- Delay any grapher data until a grapher step; OR
- Do a once-off metadata query to grapher, and check it in as a JSON file as part of the recipe for this dataset

## Full error

```
Detecting which steps need rebuilding...
Running 2 steps:
1. data://garden/worldbank_wdi/2022-05-26/wdi...
/Users/lars/Documents/owid/etl/etl/steps/data/garden/worldbank_wdi/2022-05-26/wdi.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"] = countries
2022-09-05 11:40:33,711 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/run_python_step", line 6, in <module>
    sys.exit(main())
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 26, in main
    _import_and_run(path, dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 44, in _import_and_run
    module.run(dest_dir)  # type: ignore
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/worldbank_wdi/2022-05-26/wdi.py", line 67, in run
    tb_garden = add_variable_metadata(tb_garden)
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/worldbank_wdi/2022-05-26/wdi.py", line 368, in add_variable_metadata
    vm = VariableMatcher()
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/worldbank_wdi/2022-05-26/wdi.py", line 531, in __init__
    self.grapher_variables = self.fetch_grapher_variables()
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/worldbank_wdi/2022-05-26/wdi.py", line 581, in fetch_grapher_variables
    df_vars = pd.read_sql(query, get_connection())
  File "/Users/lars/Documents/owid/etl/etl/db.py", line 22, in get_connection
    return MySQLdb.connect(
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on '127.0.0.1' (36)")
```

**Comment by Marigold** [comment]
I can take this one. The first proposed solution won't work because of [this issue](https://github.com/owid/etl/issues/329), but generating JSON file as a recipe should be straightforward.
