### ISSUE TITLE
Error building data://garden/shift/2022-07-18/fossil_fuel_production

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#467]
On current `master`:

```
3. data://garden/shift/2022-07-18/fossil_fuel_production...
2022-09-14 11:00.39 [info     ] fossil_fuel_production.start
2022-09-14 11:00.39 [info     ] fossil_fuel_production.harmonize_countries
2022-09-14 11:00.39 [info     ] fossil_fuel_production.add_region_aggregates
2022-09-14 11:00:40,843 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl/.venv/bin/run_python_step", line 6, in <module>
    sys.exit(main())
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 33, in main
    _import_and_run(path, dest_dir)
  File "/Users/lars/Documents/owid/etl/etl/run_python_step.py", line 51, in _import_and_run
    module.run(dest_dir)  # type: ignore
  File "/Users/lars/Documents/owid/etl/etl/steps/data/garden/shift/2022-07-18/fossil_fuel_production.py", line 423, in run
    ds_garden.metadata.update_from_yaml(METADATA_PATH)
  File "/Users/lars/Documents/owid/etl/vendor/owid-catalog-py/owid/catalog/meta.py", line 180, in update_from_yaml
    raise ValueError(f"Source {self.sources[0].name} would be overwritten by source {source_annot['name']}")
ValueError: Source The Shift Data Portal would be overwritten by source Our World in Data based on The Shift Dataportal (2022)
```

**Comment by larsyencken** [comment]
Thanks for tackling the `energy` one @Marigold , but it's still broken in `data://garden/shift/...`. This is definitely a case where CI (or running it locally) would pick up the issue.

**Comment by larsyencken** [comment]
I'll do the same patch on these ones.

**Comment by pabloarosado** [comment]
I think @Marigold changed a different `fossil_fuel_production` file (the one in `energy`, instead of `shift`). I don't know if it was necessary there. I can revert that (just in case it sources did not have to be replaced) and change the `shift` `fossil_fuel_prediction`.

**Comment by pabloarosado** [comment]
> I'll do the same patch on these ones.

Sorry, I didn't see this. I have already patched it [here](https://github.com/owid/etl/pull/469).

**Comment by larsyencken** [comment]
@pabloarosado @Marigold Heads up that ETL was still broken after both these patches, a third one was needed since `data://garden/ember/...` got missed. I just pushed it now. Could be a good idea to get into the habit of building the full ETL locally and not merging any change (fix or otherwise) until the ETL builds cleanly with that change.
