### ISSUE TITLE
Bug: sqlalchemy.exc.IntegrityError

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#486]
I am adding a new dataset to Grapher, and for some reason, I can't unless I remove the dataset.

This is the error I am getting:

```
~ etl --grapher grapher/owid/latest/key_indicators 
Detecting which steps need rebuilding...
Running 3 steps:
1. data://garden/owid/latest/key_indicators...
OK (3s)

2. data://grapher/owid/latest/key_indicators...
OK (2s)

3. grapher://grapher/owid/latest/key_indicators...
2022-09-19 15:34.33 [info     ] upsert_dataset.verify_namespace namespace=owid
2022-09-19 15:34.33 [info     ] upsert_dataset.upsert_dataset.start short_name=key_indicators
2022-09-19 15:34.33 [info     ] upsert_dataset.upsert_dataset.end id=5710 short_name=key_indicators
2022-09-19 15:34.33 [info     ] yield_wide_table.create_variable short_name=land_area title=Land area (sq. km)
2022-09-19 15:34.33 [info     ] upsert_table.upsert_variable   variable=land_area
2022-09-19 15:34.34 [info     ] upsert_table.upserted_data_values size=13272
2022-09-19 15:34.34 [info     ] yield_wide_table.create_variable short_name=population title=Population
2022-09-19 15:34.34 [info     ] yield_wide_table.create_variable short_name=world_pop_share title=Share of world population
2022-09-19 15:34.34 [info     ] upsert_table.upsert_variable   variable=population
2022-09-19 15:34.34 [info     ] yield_wide_table.create_variable short_name=population_historical title=Population (historical estimates)
2022-09-19 15:34.34 [info     ] upsert_table.upsert_variable   variable=world_pop_share
2022-09-19 15:34.34 [info     ] yield_wide_table.create_variable short_name=population_projection title=Population (future projections)
2022-09-19 15:34.34 [info     ] upsert_table.upsert_variable   variable=population_historical
2022-09-19 15:34.34 [info     ] yield_wide_table.create_variable short_name=world_pop_share_historical title=Share of world population (historical estimates)
2022-09-19 15:34.34 [info     ] upsert_table.upsert_variable   variable=population_projection
2022-09-19 15:34.34 [info     ] yield_wide_table.create_variable short_name=world_pop_share_projection title=Share of world population (future projections)
2022-09-19 15:34.34 [info     ] upsert_table.upsert_variable   variable=world_pop_share_historical
2022-09-19 15:34.34 [info     ] upsert_table.upsert_variable   variable=world_pop_share_projection
2022-09-19 15:34.36 [info     ] upsert_table.upserted_data_values size=57172
2022-09-19 15:34.37 [info     ] upsert_table.upserted_data_values size=19671
2022-09-19 15:34.39 [info     ] upsert_table.upserted_data_values size=76843
2022-09-19 15:34:39,895 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'world_pop_share-5710' for key 'variables.unique_short_name_per_dataset'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/bin/etl", line 5, in <module>
    main_cli()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lucas/repos/etl/etl/command.py", line 119, in main_cli
    main(**kwargs)  # type: ignore
  File "/home/lucas/repos/etl/etl/command.py", line 147, in main
    run_dag(
  File "/home/lucas/repos/etl/etl/command.py", line 236, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/command.py", line 243, in timed_run
    f()
  File "/home/lucas/repos/etl/etl/command.py", line 236, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 535, in run
    variable_upsert_results += list(results)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 519, in <lambda>
    upsert = lambda t: upsert_table(  # noqa: E731
  File "/home/lucas/repos/etl/etl/grapher_import.py", line 234, in upsert_table
    ).upsert(session)
  File "/home/lucas/repos/etl/etl/grapher_model.py", line 736, in upsert
    return session.exec(q).one()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 60, in exec
    results = super().execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 316, in orm_pre_session_exec
    session._autoflush()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3522, in _flush
    with util.safe_reraise():
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb.IntegrityError) (1062, "Duplicate entry 'world_pop_share-5710' for key 'variables.unique_short_name_per_dataset'")
[SQL: INSERT INTO variables (`datasetId`, name, `shortName`, description, unit, `createdAt`, `updatedAt`, coverage, timespan, `sourceId`, display, `columnOrder`, code, `shortUnit`, `originalMetadata`, `grapherConfig`, `catalogPath`, dimensions) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (5710, 'Share of world population', 'world_pop_share', "Share of the world's population by country, available from 10,000 BCE to 2100 based on Gapminder data, HYDE, and UN Population Division (2022) estima ... (146 characters truncated) ... he United Nations - Population Division (2022).\n2022-2100: Projections based on Medium variant by the United Nations - Population Division (2022).\n", '%', datetime.datetime(2022, 9, 19, 13, 34, 34, 374746), datetime.datetime(2022, 9, 19, 13, 34, 34, 374749), '', '-10000-2100', 22761, '{"name": "Share of world population", "includeInTable": true, "conversionFactor": 100, "shortUnit": null, "unit": "%"}', 0, None, None, None, None, 'grapher/owid/latest/key_indicators/population', None)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by larsyencken** [comment]
It sounds in this case there's an existing variable, and the the expected behaviour is that it simply overwrites the existing variable that's there. Marked it as "important". It would be higher prio if it was actively blocking `key_indicators` work, but since you have a workaround @lucasrodes I think it's ok.

**Comment by Marigold** [comment]
@lucasrodes is this still happening?

**Comment by lucasrodes** [comment]
I believe it is not happening anymore ー will re-open if it does!

**Comment by lucasrodes** [comment]
This was happening because I was using the same `title`  for two different variables in the same table.

This was fixed in https://github.com/owid/etl/pull/490/commits/6566b3735757289d9c3cba23af36171b61eb4fcc
