### ISSUE TITLE
data://garden/cait/2022-08-10/ghg_emissions_by_sector: Categorical categories must be unique

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#507]
```
3. data://garden/cait/2022-08-10/ghg_emissions_by_sector...
/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/owid/datautils/common.py:29: UserWarning: 18 missing values in mapping.
  warnings.warn(warning_message)
2022-09-23 17:03:05,165 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/lars/Documents/owid/etl.demo/.venv/bin/run_python_step", line 6, in <module>
    sys.exit(main())
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl.demo/etl/run_python_step.py", line 33, in main
    _import_and_run(path, dest_dir)
  File "/Users/lars/Documents/owid/etl.demo/etl/run_python_step.py", line 51, in _import_and_run
    module.run(dest_dir)  # type: ignore
  File "/Users/lars/Documents/owid/etl.demo/etl/steps/data/garden/cait/2022-08-10/ghg_emissions_by_sector.py", line 176, in run
    df["sector"] = dataframes.map_series(
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/owid/datautils/dataframes.py", line 419, in map_series
    return cast(pd.Series, series.cat.rename_categories(category_mapping))
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/core/accessor.py", line 95, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/core/arrays/categorical.py", line 2880, in _delegate_method
    res = method(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/core/arrays/categorical.py", line 1142, in rename_categories
    cat._set_categories(new_categories)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/core/arrays/categorical.py", line 809, in _set_categories
    new_dtype = CategoricalDtype(categories, ordered=self.ordered)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/core/dtypes/dtypes.py", line 186, in __init__
    self._finalize(categories, ordered, fastpath=False)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/core/dtypes/dtypes.py", line 340, in _finalize
    categories = self.validate_categories(categories, fastpath=fastpath)
  File "/Users/lars/Documents/owid/etl.demo/.venv/lib/python3.10/site-packages/pandas/core/dtypes/dtypes.py", line 537, in validate_categories
    raise ValueError("Categorical categories must be unique")
ValueError: Categorical categories must be unique
```

**Comment by Marigold** [comment]
@larsyencken this was already fixed in datautils 0.4.11, could you run poetry install and try again? (the [line that got fixed](https://github.com/owid/owid-datautils-py/blob/main/owid/datautils/dataframes.py#L419))

**Comment by pabloarosado** [comment]
This is not happening anymore, feel free to close this @larsyencken. Actually now you'll see some new warnings (missing sectors and missing countries in mapping). But they are not true, as discussed [here](https://owid.slack.com/archives/C02706JNFC6/p1664189947203849). I'll fix this in datautils to avoid having those warnings.

**Comment by larsyencken** [comment]
Thanks for the updates 🙌
