### ISSUE TITLE
`harmonize` tool does not work

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#712]
`harmonize` tool is failing to run on my end. This makes me think that we should probably have some testing or CI/CD for changes in our command tools (including walkthrough).

**Complete error traceback**
```
✗ harmonize data/garden/health/latest/karlinsky/death_registration.feather country countries.json
181 countries/regions to harmonize
  └ 177 automatically matched
  └ 4 ambiguous countries/regions

Beginning interactive harmonization...

[1/4] Bosnia
Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/process.py", line 108, in extractWithoutOrder
    for key, choice in choices.items():
AttributeError: 'dict_keys' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/bin/harmonize", line 6, in <module>
    sys.exit(harmonize())
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lucas/repos/etl/etl/harmonize.py", line 51, in harmonize
    mapping = interactive_harmonize(geo_column, mapping, institution=institution)
  File "/home/lucas/repos/etl/etl/harmonize.py", line 104, in interactive_harmonize
    suggestions = mapper.suggestions(region, institution=institution)
  File "/home/lucas/repos/etl/etl/harmonize.py", line 158, in suggestions
    results = process.extract(region.lower(), self.aliases.keys(), limit=5)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/process.py", line 168, in extract
    return heapq.nlargest(limit, sl, key=lambda i: i[1]) if limit is not None else \
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/heapq.py", line 563, in nlargest
    result = [(key(elem), i, elem) for i, elem in zip(range(0, -n, -1), it)]
  File "/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/heapq.py", line 563, in <listcomp>
    result = [(key(elem), i, elem) for i, elem in zip(range(0, -n, -1), it)]
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/process.py", line 117, in extractWithoutOrder
    score = scorer(processed_query, processed)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/fuzz.py", line 276, in WRatio
    base = ratio(p1, p2)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/utils.py", line 38, in decorator
    return func(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/utils.py", line 29, in decorator
    return func(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/utils.py", line 47, in decorator
    return func(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/fuzz.py", line 28, in ratio
    return utils.intr(100 * m.ratio())
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/thefuzz/StringMatcher.py", line 64, in ratio
    self._ratio = ratio(self._str1, self._str2)
NameError: name 'ratio' is not defined
```

**Comment by lucasrodes** [comment]
I am unsure what caused this issue, but I can no longer recreate it. Fresh installed the library (`poetry install`) and it worked perfectly.
