### ISSUE TITLE
Strange (pandas-related?) error when executing grapher db step

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#733]
On branch `ingest-energy-investments-data`, when running `ENV=.env.staging etl renewable_energy_investments --grapher` I get the same error repeated many times, namely:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 973, in setitem
    casted = np_can_hold_element(values.dtype, value)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 2023, in np_can_hold_element
    raise LossySetitemError
pandas.core.dtypes.cast.LossySetitemError
```
And eventually:
```
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 977, in setitem
    return nb.setitem(indexer, value)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 977, in setitem
    return nb.setitem(indexer, value)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 977, in setitem
    return nb.setitem(indexer, value)
  [Previous line repeated 987 more times]
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 976, in setitem
    nb = self.coerce_to_target_dtype(value)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 448, in coerce_to_target_dtype
    new_dtype = find_result_type(self.values, other)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1531, in find_result_type
    new_dtype = find_common_type([left.dtype, dtype])
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1622, in find_common_type
    res = t._get_common_dtype(types)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/dtypes.py", line 625, in _get_common_dtype
    return find_common_type(non_cat_dtypes)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1635, in find_common_type
    has_bools = any(is_bool_dtype(t) for t in types)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1635, in <genexpr>
    has_bools = any(is_bool_dtype(t) for t in types)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/common.py", line 1329, in is_bool_dtype
    if isinstance(arr_or_dtype, ABCIndex):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/generic.py", line 47, in _instancecheck
    return _check(inst) and not isinstance(inst, type)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/generic.py", line 41, in _check
    return getattr(inst, attr, "_typ") in comp
RecursionError: maximum recursion depth exceeded while calling a Python object
```

The error was happening on local grapher too, but after restarting grapher now it doesn't happen, for some reason. So now the error happens on staging but not on local grapher (I haven't tried running it on live grapher). The error seems to happen when function `country_to_entity_id` is executed.

**Comment by pabloarosado** [comment]
The very beginning of the error (many thousands of lines above) is:
```
2023-01-03 18:21.09 [info     ] Creating entities in DB        countries={'world'}
2023-01-03 18:21:10,403 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 1105, in __setitem__
    self._set_with_engine(key, value)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 1175, in _set_with_engine
    loc = self.index.get_loc(key)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 394, in get_loc
    self._check_indexing_error(key)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5968, in _check_indexing_error
    raise InvalidIndexError(key)
pandas.errors.InvalidIndexError: 0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
Name: country, dtype: bool
```

After this it starts with the repeated error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 1020, in putmask
    casted = np_can_hold_element(values.dtype, new)
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 2023, in np_can_hold_element
    raise LossySetitemError
pandas.core.dtypes.cast.LossySetitemError

During handling of the above exception, another exception occurred:
```

**Comment by Marigold** [comment]
Fixed in https://github.com/owid/etl/pull/736. Could be related to pandas 1.5.1 -> 1.5.2 upgrade, `Series.map` now maps Category to Category natively.

**Comment by pabloarosado** [comment]
Thanks a lot @Marigold! It works again.
