### ISSUE TITLE
Walkthrough(charts): KeyError raised when editing variable mapping

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#813]
### One-liner
`walkthrough charts` not working when editing the submitted variable mapping. 

### Environment

- `python -V`: 3.10.9
- Operating system: Linux
- Working with local, staging or live: any of them

### Steps to reproduce

1. Run `walkthrough charts`
2. Select "Life Expectancy (various sources)" as the old dataset and "World Population Prospects - UN (2022)" as the new dataset. Leave the rest of the parameters as they are and click `Submit`.
3. Select the following variable mapping (note that this is not the correct mapping):
    - `Life expectancy at birth (historical)` → `Life expectancy - Sex: all - Age: 80 - Variant: medium` (should be the first option)
    - `Life expectancy at 15` → `Life expectancy - Sex: male - Age: at birth - Variant: constant fertility` (should be the second option)
4. Click on `Edit` to go back and correct the mapping submitted.
5. Change one of the mappings to any other variable and click on `Submit`, e.g.:
    - `Life expectancy at 15` → `Life expectancy - Sex: male - Age: 65 - Variant: constant fertility` (should be the third option)

You should get an error like

```
Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/pywebio/session/threadbased.py", line 257, in run
    callback(event['data'])
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/pywebio/output.py", line 805, in click_callback
    return onclick[btn_idx]()
  File "/home/lucas/repos/etl/walkthrough/charts.py", line 481, in _repeat_step
    self.run_app()
  File "/home/lucas/repos/etl/walkthrough/charts.py", line 394, in run_app
    self.confirm_variable_mapping(next_step=self.final_steps)
  File "/home/lucas/repos/etl/walkthrough/charts.py", line 484, in confirm_variable_mapping
    self.show_variable_mapping_table(separate=True)
  File "/home/lucas/repos/etl/walkthrough/charts.py", line 635, in show_variable_mapping_table
    _show_table(self.variable_mapping_manual)
  File "/home/lucas/repos/etl/walkthrough/charts.py", line 615, in _show_table
    summary = self._build_variable_description(new_id)
  File "/home/lucas/repos/etl/walkthrough/charts.py", line 654, in _build_variable_description
    timespan = self.variable_id_to_all[id_].get("timespan")
KeyError: 530862
```

The issue lies in the second variable mapping submission now having a new variable that did not appear in the first submission.

https://user-images.githubusercontent.com/18101289/215619329-c41a98c6-8933-49b8-95a8-6e4e1042c808.mov

**Comment by lucasrodes** [comment]
keep this issue

**Comment by lucasrodes** [comment]
In the new version of the chart revision, the flow has changed. This issue is no longer appearing.
