### ISSUE TITLE
sqlalchemy.exc.IntegrityError: Error when pushing a grapher dataset.

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#848]
I am working in branch `data/excess-mortality`. I am trying to push a Grapher dataset to _live_, but I am getting the following error:

```
$ poetry run etl grapher://grapher/excess_mortality/latest/excess_mortality --grapher
...
[SQL: INSERT INTO datasets (name, `shortName`, version, namespace, description, `createdAt`, `updatedAt`, `isPrivate`, `createdByUserId`, `metadataEditedAt`, `metadataEditedByUserId`, `dataEditedAt`, `dataEditedByUserId`, `nonRedistributable`, `isArchived`, `sourceChecksum`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('Excess Mortality (various sources)', 'excess_mortality', 'latest', 'excess_mortality', '', datetime.datetime(2023, 2, 17, 0, 22, 16, 899853), datetime.datetime(2023, 2, 17, 0, 22, 16, 899854), 0, 52, datetime.datetime(2023, 2, 17, 0, 22, 16, 899859), 52, datetime.datetime(2023, 2, 17, 0, 22, 16, 899861), 52, 0, 0, None)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

I also tried in staging, and the same error happened. The only difference in this update is that the dataset contains a new column.

The complete traceback:

```
$ ENV=.env.staging poetry run etl grapher://grapher/excess_mortality/latest/excess_mortality --grapher

/home/lucas/.pyenv/versions/3.10.9/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Detecting which steps need rebuilding...
OK (4s)                                                               
Running 1 steps:
1. grapher://grapher/excess_mortality/latest/excess_mortality...
2023-02-17 01:22.16 [info     ] upsert_dataset.verify_namespace namespace=excess_mortality
2023-02-17 01:22.16 [info     ] upsert_dataset.upsert_dataset.start short_name=excess_mortality
2023-02-17 01:22:17,086 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'Excess Mortality (various sources)-excess_mortality' for key 'datasets.datasets_name_namespace_d3d60d22_uniq'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lucas/repos/etl/etl/command.py", line 119, in main_cli
    main(**kwargs)  # type: ignore
  File "/home/lucas/repos/etl/etl/command.py", line 147, in main
    run_dag(
  File "/home/lucas/repos/etl/etl/command.py", line 245, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/command.py", line 252, in timed_run
    f()
  File "/home/lucas/repos/etl/etl/command.py", line 245, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/home/lucas/repos/etl/etl/steps/__init__.py", line 697, in run
    dataset_upsert_results = upsert_dataset(
  File "/home/lucas/repos/etl/etl/grapher_import.py", line 105, in upsert_dataset
    ).upsert(session)
  File "/home/lucas/repos/etl/etl/grapher_model.py", line 351, in upsert
    return session.exec(q).one()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 60, in exec
    results = super().execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1662, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2259, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2248, in _autoflush
    self.flush()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3583, in _flush
    with util.safe_reraise():
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb.IntegrityError) (1062, "Duplicate entry 'Excess Mortality (various sources)-excess_mortality' for key 'datasets.datasets_name_namespace_d3d60d22_uniq'")
[SQL: INSERT INTO datasets (name, `shortName`, version, namespace, description, `createdAt`, `updatedAt`, `isPrivate`, `createdByUserId`, `metadataEditedAt`, `metadataEditedByUserId`, `dataEditedAt`, `dataEditedByUserId`, `nonRedistributable`, `isArchived`, `sourceChecksum`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('Excess Mortality (various sources)', 'excess_mortality', 'latest', 'excess_mortality', '', datetime.datetime(2023, 2, 17, 0, 22, 16, 899853), datetime.datetime(2023, 2, 17, 0, 22, 16, 899854), 0, 52, datetime.datetime(2023, 2, 17, 0, 22, 16, 899859), 52, datetime.datetime(2023, 2, 17, 0, 22, 16, 899861), 52, 0, 0, None)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by lucasrodes** [comment]
Did not have time to look into detail, but might be related to https://github.com/owid/etl/issues/487

**Comment by Marigold** [comment]
Thanks for reporting @lucasrodes, taking a look.

**Comment by Marigold** [comment]
The problem is that excess mortality had previously version `2023-01-27` and now we’re trying to overwrite it with `latest`. In a perfect world, it would create a new dataset with new latest version… however for legacy reasons we can’t have two datasets with the same name (we could get rid of it, but I’d rather wait until ETL takes ownership of MySQL tables)
we could fix it in two ways:

1. Change version of the “old” dataset to latest , then it’s gonna work and replace the dataset
2. Change name from Excess Mortality (various sources) to something different

I'll do 1. and try to fix it.

**Comment by lucasrodes** [comment]
Thanks, @Marigold! Working like a charm for me.
