### ISSUE TITLE
bug: meadow/hyde/2017/general_files etl thows BadZipFile

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#86]
I was trying to run the etl for `garden/explorers/2021/food_explorer` and detected a `BadZipFile` error for `meadow/hyde/2017/general_files` etl:

```
.venv/bin/etl food_explorer
Detecting which steps need rebuilding...
Running 8 steps:
1. walden://hyde/2017/general_files...
OK (1s)

2. walden://hyde/2017/baseline...
OK (190s)

3. data://meadow/hyde/2017/general_files...
Traceback (most recent call last):
  File "/home/user/repos/etl/.venv/bin/etl", line 5, in <module>
    main()
  File "/home/user/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/repos/etl/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/repos/etl/etl/command.py", line 45, in main
    run_dag(
  File "/home/user/repos/etl/etl/command.py", line 98, in run_dag
    time_taken = timed_run(lambda: step.run())
  File "/home/user/repos/etl/etl/command.py", line 105, in timed_run
    f()
  File "/home/user/repos/etl/etl/command.py", line 98, in <lambda>
    time_taken = timed_run(lambda: step.run())
  File "/home/user/repos/etl/etl/steps/__init__.py", line 246, in run
    self._run_notebook()
  File "/home/user/repos/etl/etl/steps/__init__.py", line 342, in _run_notebook
    pm.execute_notebook(
  File "/home/user/repos/etl/.venv/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/user/repos/etl/.venv/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
/tmp/ipykernel_28488/1774091728.py in <module>
----> 1 zipfile.ZipFile(walden_ds.local_path).extractall(temp_dir)

~/.pyenv/versions/3.9.5/lib/python3.9/zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1255         try:
   1256             if mode == 'r':
-> 1257                 self._RealGetContents()
   1258             elif mode in ('w', 'x'):
   1259                 # set the modified flag so central directory gets written

~/.pyenv/versions/3.9.5/lib/python3.9/zipfile.py in _RealGetContents(self)
   1322             raise BadZipFile("File is not a zip file")
   1323         if not endrec:
-> 1324             raise BadZipFile("File is not a zip file")
   1325         if self.debug > 1:
   1326             print(endrec)

BadZipFile: File is not a zip file
```

**Comment by larsyencken** [comment]
Can you delete your `~/.owid/walden/hyde` folder and try again? There might have been an error the first time the file got downloaded.
