### ISSUE TITLE
AttributeError: 'Connection' object has no attribute '_binary_prefix'

### ISSUE THREAD

**Issue by Marigold** [owid/etl#905]
We're occasionally getting strange error when upserting to grapher. Running `ENV=.env.staging poetry run etl grapher/technology/2023-03-06/mobile_money --grapher` raises

```python
Detecting which steps need rebuilding...
OK (0s)                                                               
Running 2 steps:
1. data://grapher/technology/2023-03-06/mobile_money...
OK (2s)

2. grapher://grapher/technology/2023-03-06/mobile_money...
2023-03-09 17:03.35 [info     ] upsert_dataset.verify_namespace namespace=technology
2023-03-09 17:03.36 [info     ] upsert_dataset.upsert_dataset.start short_name=mobile_money
2023-03-09 17:03.36 [info     ] upsert_dataset.upsert_dataset.end id=5914 short_name=mobile_money
2023-03-09 17:03.37 [info     ] yield_wide_table.create_variable short_name=active_accounts_90d title=Active accounts (90 day)
2023-03-09 17:03.37 [info     ] upsert_table.upsert_variable   variable=active_accounts_90d
2023-03-09 17:03:38,106 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "/Users/edouard/git/etl/etl/grapher_import.py", line 432, in insert_to_data_values
    df.to_sql(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/io/sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/io/sql.py", line 1738, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/io/sql.py", line 1325, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/io/sql.py", line 946, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/io/sql.py", line 853, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 193, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 230, in executemany
    return self._do_execute_many(
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 255, in _do_execute_many
    v = values % escape(next(args), conn)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 110, in _escape_args
    ret = tuple(literal(ensure_bytes(arg)) for arg in args)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 110, in <genexpr>
    ret = tuple(literal(ensure_bytes(arg)) for arg in args)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 279, in literal
    s = self._bytes_literal(o)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 259, in _bytes_literal
    if self._binary_prefix:
AttributeError: 'Connection' object has no attribute '_binary_prefix'
```

**Comment by Marigold** [comment]
@edomt I couldn't replicate it on my local with python 3.10. There are two things you could try:

1. Run `poetry install` and then try again
2. If 1. doesn't work, run `rm -Rf .venv`, then `make test` and try again to rebuild `.venv`

If those doesn't work, then we'll probably have to wait for a new version of mysqlclient library. (In the meantime, just pushing to `staging` branch will automatically deploy to our staging server)
